// apps/web-svelte/src/lib/components/ImportButton.svelte
<script lang="ts">
  import { Upload } from "@lucide/svelte";
  import DestinationPicker from "$lib/components/DestinationPicker.svelte";
  import LibraryRootPicker from "$lib/components/LibraryRootPicker.svelte";
  import { createUploader } from "$lib/upload/uploader.svelte";
  import {
    acceptForCategory,
    categoryForTarget,
    type UploadTarget,
  } from "$lib/upload/upload-types";

  interface Props {
    target: UploadTarget;
    onUploaded?: () => void | Promise<void>;
    label?: string;
    disabled?: boolean;
  }

  let { target, onUploaded, label = "Import", disabled = false }: Props = $props();
  // svelte-ignore state_referenced_locally
  const uploader = createUploader({ target, onUploaded });
  const accept = $derived(acceptForCategory(categoryForTarget(target)));
  let input: HTMLInputElement | undefined = $state();
</script>

<input
  bind:this={input}
  type="file"
  multiple
  {accept}
  class="hidden"
  onchange={(event) => {
    const files = event.currentTarget.files;
    if (files?.length) void uploader.uploadFiles(files);
    event.currentTarget.value = "";
  }}
/>

<button
  type="button"
  onclick={() => input?.click()}
  {disabled}
  class="inline-flex items-center gap-1.5 border border-border-subtle bg-surface-2/70 px-3 py-1.5 text-[0.78rem] text-text-muted transition-colors hover:border-border-accent hover:text-text-primary disabled:opacity-50"
>
  <Upload class="h-3.5 w-3.5" />
  {label}
</button>

<LibraryRootPicker
  open={uploader.needsRootPicker}
  roots={uploader.candidateRoots}
  onConfirm={uploader.confirmRootPick}
  onCancel={uploader.cancelRootPick}
/>
<DestinationPicker
  open={uploader.needsGalleryPicker}
  title="Choose a gallery"
  description="Pick the folder-backed gallery these image files should land in."
  items={uploader.candidateGalleries.map((gallery) => ({
    id: gallery.id,
    title: gallery.title,
    subtitle: `${gallery.imageCount} image${gallery.imageCount === 1 ? "" : "s"}`,
  }))}
  onConfirm={uploader.confirmGalleryPick}
  onCancel={uploader.cancelGalleryPick}
/>
<DestinationPicker
  open={uploader.needsAudioLibraryPicker}
  title="Choose an audio library"
  description="Pick the library these tracks should land in."
  items={uploader.candidateAudioLibraries.map((library) => ({
    id: library.id,
    title: library.title,
    subtitle: `${library.trackCount} track${library.trackCount === 1 ? "" : "s"}`,
  }))}
  onConfirm={uploader.confirmAudioLibraryPick}
  onCancel={uploader.cancelAudioLibraryPick}
/>

// apps/web/src/components/upload/import-button.tsx
"use client";

import { useRef } from "react";
import { Upload } from "lucide-react";
import { Button } from "@obscura/ui/primitives/button";
import {
  acceptForCategory,
  categoryForTarget,
  type UploadTarget,
} from "./upload-types";
import { useUploader } from "./use-uploader";
import { LibraryRootPicker } from "./library-root-picker";
import { AudioLibraryPicker } from "./audio-library-picker";

interface ImportButtonProps {
  target: UploadTarget;
  onUploaded?: () => void;
  label?: string;
  disabled?: boolean;
}

/**
 * Header-bar button that opens a file picker and runs the upload through
 * the same pipeline as <UploadDropZone>. Shares use-uploader so the scene
 * root picker and per-file error surfacing behave the same.
 *
 * Intentionally does NOT render the status strip — pair this with an
 * UploadDropZone on the same view, or mount the status strip elsewhere.
 * In practice every integration already wraps the page in UploadDropZone,
 * so the strip is visible regardless of which entry point was used.
 */
export function ImportButton({
  target,
  onUploaded,
  label,
  disabled,
}: ImportButtonProps) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  const uploader = useUploader({ target, onUploaded });
  const category = categoryForTarget(target);
  const accept = acceptForCategory(category);

  const handleClick = () => {
    inputRef.current?.click();
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      void uploader.uploadFiles(files);
    }
    // Allow selecting the same file twice in a row.
    e.target.value = "";
  };

  return (
    <>
      <input
        ref={inputRef}
        type="file"
        multiple
        accept={accept}
        onChange={handleChange}
        className="hidden"
      />
      <Button
        variant="secondary"
        size="md"
        onClick={handleClick}
        disabled={disabled}
      >
        <Upload className="h-3.5 w-3.5" />
        {label ?? "Import"}
      </Button>
      <LibraryRootPicker
        open={uploader.needsRootPicker}
        roots={uploader.candidateRoots}
        onConfirm={uploader.confirmRootPick}
        onCancel={uploader.cancelRootPick}
      />
      <AudioLibraryPicker
        open={uploader.needsAudioLibraryPicker}
        libraries={uploader.candidateAudioLibraries}
        onConfirm={uploader.confirmAudioLibraryPick}
        onCancel={uploader.cancelAudioLibraryPick}
      />
    </>
  );
}
