// apps/web-svelte/src/lib/components/ImageLightbox.svelte
<script lang="ts">
  import { onMount, untrack } from "svelte";
  import {
    X,
    ChevronLeft,
    ChevronRight,
    ZoomIn,
    ZoomOut,
    RotateCcw,
    Download,
    Info,
    Star,
  } from "@lucide/svelte";
  import type { ImageListItemDto } from "@obscura/contracts";
  import { isVideoImage } from "@obscura/contracts";
  import { toApiUrl } from "$lib/api/core";
  import { updateImage } from "$lib/api/media";
  import NsfwBlur from "./NsfwBlur.svelte";

  interface Props {
    images: ImageListItemDto[];
    initialIndex: number;
    onClose: () => void;
    onIndexChange?: (index: number) => void;
    onRatingChange?: (imageId: string, rating: number | null) => void;
    autoAdvanceSeconds?: number;
    onAutoAdvance?: () => void;
    onPreviousRequest?: () => void;
    onNextRequest?: () => void;
  }

  let {
    images,
    initialIndex,
    onClose,
    onIndexChange,
    onRatingChange,
    autoAdvanceSeconds = 0,
    onAutoAdvance,
    onPreviousRequest,
    onNextRequest,
  }: Props = $props();

  const MIN_SCALE = 0.3;
  const MAX_SCALE = 8;
  const DOUBLE_TAP_MS = 300;

  let index = $state(untrack(() => initialIndex));
  let scale = $state(1);
  let translateX = $state(0);
  let translateY = $state(0);
  let fitScale = $state(1);
  let infoOpen = $state(false);
  let ratingOverrides = $state<Record<string, number | null>>({});
  let savingRating = $state(false);

  let stageEl: HTMLDivElement | undefined = $state();
  let imgEl: HTMLImageElement | HTMLVideoElement | undefined = $state();
  let naturalW = $state(0);
  let naturalH = $state(0);
  let ready = $state(false);

  const current = $derived(images[index]);
  const currentRating = $derived.by(() => {
    if (!current) return null;
    const override = ratingOverrides[current.id];
    return override !== undefined ? override : current.rating;
  });
  const isCurrentVideo = $derived(current ? isVideoImage(current) : false);
  const src = $derived.by(() => {
    if (!current) return null;
    if (isCurrentVideo) {
      return (
        toApiUrl(current.previewPath) ??
        toApiUrl(current.fullPath) ??
        toApiUrl(current.thumbnailPath) ??
        null
      );
    }
    return (
      toApiUrl(current.fullPath) ??
      toApiUrl(current.previewPath) ??
      toApiUrl(current.thumbnailPath) ??
      null
    );
  });

  $effect(() => {
    onIndexChange?.(index);
  });

  $effect(() => {
    // Reset fit state whenever the image changes; `ready` stays false
    // until the new image loads and applyFit() computes the correct
    // scale, so the viewer doesn't flash the natural-size image.
    if (current) {
      ready = false;
      naturalW = 0;
      naturalH = 0;
      translateX = 0;
      translateY = 0;
      scale = 1;
      fitScale = 1;
    }
  });

  function goPrev() {
    if (onPreviousRequest) {
      onPreviousRequest();
      return;
    }
    if (images.length === 0) return;
    index = (index - 1 + images.length) % images.length;
  }

  function goNext() {
    if (onNextRequest) {
      onNextRequest();
      return;
    }
    if (images.length === 0) return;
    index = (index + 1) % images.length;
  }

  $effect(() => {
    if (!current || autoAdvanceSeconds <= 0) return;
    const timeout = window.setTimeout(() => {
      if (onAutoAdvance) {
        onAutoAdvance();
      } else {
        goNext();
      }
    }, autoAdvanceSeconds * 1000);
    return () => window.clearTimeout(timeout);
  });

  function resetTransform() {
    scale = fitScale || 1;
    translateX = 0;
    translateY = 0;
  }

  function clampTranslate() {
    // Keep the image from drifting off-screen entirely.
    if (!stageEl || !naturalW || !naturalH) return;
    const rect = stageEl.getBoundingClientRect();
    const dispW = naturalW * scale;
    const dispH = naturalH * scale;
    const maxX = Math.max(0, (dispW - rect.width) / 2);
    const maxY = Math.max(0, (dispH - rect.height) / 2);
    // allow a small margin so the image edge is always partly visible
    const marginX = Math.max(40, rect.width * 0.1);
    const marginY = Math.max(40, rect.height * 0.1);
    translateX = Math.min(maxX + marginX, Math.max(-(maxX + marginX), translateX));
    translateY = Math.min(maxY + marginY, Math.max(-(maxY + marginY), translateY));
  }

  function applyFit() {
    if (!stageEl || !naturalW || !naturalH) return;
    const rect = stageEl.getBoundingClientRect();
    const s = Math.min(
      (rect.width * 0.96) / naturalW,
      (rect.height * 0.94) / naturalH,
      1,
    );
    fitScale = s;
    scale = s;
    translateX = 0;
    translateY = 0;
    ready = true;
  }

  function handleImageLoad(event: Event) {
    const el = event.currentTarget as HTMLImageElement | HTMLVideoElement;
    if (el instanceof HTMLImageElement) {
      naturalW = el.naturalWidth;
      naturalH = el.naturalHeight;
    } else {
      naturalW = el.videoWidth || 1280;
      naturalH = el.videoHeight || 720;
    }
    applyFit();
  }

  function zoomBy(delta: number, centerX?: number, centerY?: number) {
    const old = scale;
    let next = old * (1 + delta);
    next = Math.min(MAX_SCALE, Math.max(MIN_SCALE * fitScale, next));
    if (next === old) return;
    if (centerX != null && centerY != null && stageEl) {
      const rect = stageEl.getBoundingClientRect();
      const cx = centerX - rect.left - rect.width / 2;
      const cy = centerY - rect.top - rect.height / 2;
      // keep the point under the cursor anchored
      translateX = cx - ((cx - translateX) * next) / old;
      translateY = cy - ((cy - translateY) * next) / old;
    }
    scale = next;
    clampTranslate();
  }

  function handleWheel(e: WheelEvent) {
    e.preventDefault();
    zoomBy(e.deltaY < 0 ? 0.12 : -0.12, e.clientX, e.clientY);
  }

  let pointerStart: { x: number; y: number; t: number } | null = null;
  let panning = $state(false);
  let lastTapAt = 0;

  function handlePointerDown(e: PointerEvent) {
    if (e.pointerType === "mouse" && e.button !== 0) return;
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
    pointerStart = { x: e.clientX, y: e.clientY, t: Date.now() };
    panning = scale > fitScale + 0.02;
  }

  function handlePointerMove(e: PointerEvent) {
    if (!pointerStart) return;
    if (!panning) return;
    translateX += e.movementX;
    translateY += e.movementY;
    clampTranslate();
  }

  function handlePointerUp(e: PointerEvent) {
    const start = pointerStart;
    pointerStart = null;
    if (!start) return;
    const dx = e.clientX - start.x;
    const dy = e.clientY - start.y;
    const elapsed = Date.now() - start.t;
    const absX = Math.abs(dx);
    const absY = Math.abs(dy);
    const moved = Math.hypot(dx, dy) > 6;

    if (!panning && !moved && e.pointerType === "mouse") {
      // single click on backdrop (not on image) — close
      const target = e.target as HTMLElement;
      if (!target.closest("[data-lightbox-image]")) {
        onClose();
        return;
      }
    }

    if (panning) {
      panning = false;
      return;
    }

    // Swipe-to-navigate / swipe-down-to-close (only when unzoomed).
    if (scale <= fitScale + 0.02 && e.pointerType !== "mouse") {
      if (elapsed < 700 && Math.max(absX, absY) > 60) {
        if (absX > absY * 1.3) {
          if (dx < 0) goNext();
          else goPrev();
          return;
        }
        if (absY > absX * 1.3 && dy > 0) {
          onClose();
          return;
        }
      }
    }

    // Double-tap / double-click to toggle zoom.
    if (!moved && e.pointerType !== "mouse") {
      const now = Date.now();
      if (now - lastTapAt < DOUBLE_TAP_MS) {
        lastTapAt = 0;
        if (scale > fitScale + 0.02) {
          resetTransform();
        } else {
          scale = fitScale * 2.5;
        }
        return;
      }
      lastTapAt = now;
    }
  }

  function handleDoubleClick(e: MouseEvent) {
    if (scale > fitScale + 0.02) {
      resetTransform();
    } else {
      zoomBy(1.5, e.clientX, e.clientY);
    }
  }

  async function handleRate(value: number) {
    if (!current) return;
    const next = currentRating === value ? null : value;
    const prev = currentRating;
    ratingOverrides = { ...ratingOverrides, [current.id]: next };
    savingRating = true;
    try {
      await updateImage(current.id, { rating: next });
      onRatingChange?.(current.id, next);
    } catch {
      ratingOverrides = { ...ratingOverrides, [current.id]: prev };
    } finally {
      savingRating = false;
    }
  }

  onMount(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    function onKey(e: KeyboardEvent) {
      const target = e.target as HTMLElement;
      const typing =
        target.tagName === "INPUT" ||
        target.tagName === "TEXTAREA" ||
        target.isContentEditable;
      if (typing && e.key !== "Escape") return;

      switch (e.key) {
        case "Escape":
          e.preventDefault();
          onClose();
          break;
        case "ArrowLeft":
        case "h":
        case "H":
          e.preventDefault();
          goPrev();
          break;
        case "ArrowRight":
        case "l":
        case "L":
          e.preventDefault();
          goNext();
          break;
        case "+":
        case "=":
          e.preventDefault();
          zoomBy(0.25);
          break;
        case "-":
        case "_":
          e.preventDefault();
          zoomBy(-0.2);
          break;
        case "0":
          e.preventDefault();
          resetTransform();
          break;
        case "i":
        case "I":
          e.preventDefault();
          infoOpen = !infoOpen;
          break;
        default:
          if (e.key >= "1" && e.key <= "5") {
            e.preventDefault();
            void handleRate(Number(e.key));
          }
      }
    }
    window.addEventListener("keydown", onKey);

    const ro = new ResizeObserver(() => {
      if (naturalW && naturalH) applyFit();
    });
    if (stageEl) ro.observe(stageEl);

    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
      ro.disconnect();
    };
  });

  const counterText = $derived(`${index + 1} / ${images.length}`);
  const downloadHref = $derived(current ? toApiUrl(current.fullPath) ?? undefined : undefined);
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div class="fixed inset-0 z-[100] flex flex-col bg-black/95 backdrop-blur-sm" role="dialog" aria-modal="true">
  <!-- Top bar -->
  <div class="relative z-20 flex items-center gap-2 border-b border-border-subtle bg-black/70 backdrop-blur-md px-3 py-2">
    <button
      type="button"
      onclick={onClose}
      class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
      aria-label="Close"
      title="Close (Esc)"
    >
      <X class="h-5 w-5" />
    </button>
    <div class="flex-1 min-w-0">
      {#if current?.title}
        <h2 class="truncate text-sm font-medium text-text-primary">{current.title}</h2>
      {/if}
      <div class="text-[0.6rem] uppercase tracking-[0.14em] text-text-muted font-mono">
        {counterText}
      </div>
    </div>
    <div class="flex items-center gap-1">
      {#each [1, 2, 3, 4, 5] as n (n)}
        <button
          type="button"
          onclick={() => void handleRate(n)}
          disabled={savingRating}
          class="p-1 text-text-muted hover:text-text-accent transition-colors disabled:opacity-50"
          aria-label={`Rate ${n}`}
          title={`${n}★ (press ${n})`}
        >
          <Star class={`h-4 w-4 ${(currentRating ?? 0) >= n ? "fill-accent-500 text-accent-500" : ""}`} />
        </button>
      {/each}
    </div>
    <button
      type="button"
      onclick={() => (infoOpen = !infoOpen)}
      class={`p-1.5 transition-colors ${infoOpen ? "text-text-accent" : "text-text-muted hover:text-text-primary"}`}
      aria-label="Info"
      title="Info (I)"
    >
      <Info class="h-4 w-4" />
    </button>
    {#if downloadHref}
      <a
        href={downloadHref}
        download={current?.title ?? "image"}
        class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
        aria-label="Download"
        title="Download"
      >
        <Download class="h-4 w-4" />
      </a>
    {/if}
  </div>

  <!-- Stage + optional info sidebar -->
  <div class="relative flex-1 flex min-h-0">
    <div
      bind:this={stageEl}
      class="relative flex-1 overflow-hidden select-none"
      onwheel={handleWheel}
      onpointerdown={handlePointerDown}
      onpointermove={handlePointerMove}
      onpointerup={handlePointerUp}
      onpointercancel={handlePointerUp}
      ondblclick={handleDoubleClick}
      style:cursor={scale > fitScale + 0.02 ? (panning ? "grabbing" : "grab") : "default"}
    >
      {#if images.length > 1}
        <button
          type="button"
          onclick={goPrev}
          class="hidden sm:flex items-center justify-center absolute left-3 top-1/2 -translate-y-1/2 z-10 h-10 w-10 bg-black/50 text-white/80 hover:bg-black/70 hover:text-white transition-colors"
          aria-label="Previous (←)"
        >
          <ChevronLeft class="h-6 w-6" />
        </button>
        <button
          type="button"
          onclick={goNext}
          class="hidden sm:flex items-center justify-center absolute right-3 top-1/2 -translate-y-1/2 z-10 h-10 w-10 bg-black/50 text-white/80 hover:bg-black/70 hover:text-white transition-colors"
          aria-label="Next (→)"
        >
          <ChevronRight class="h-6 w-6" />
        </button>
      {/if}

      {#if current && src}
        <div
          class="absolute inset-0 flex items-center justify-center"
          style:transform="translate({translateX}px, {translateY}px) scale({scale})"
          style:transform-origin="center center"
          style:opacity={ready ? 1 : 0}
        >
          <NsfwBlur isNsfw={current.isNsfw}>
            {#if isCurrentVideo}
              <!-- svelte-ignore a11y_media_has_caption -->
              <video
                data-lightbox-image
                bind:this={imgEl as HTMLVideoElement}
                src={src}
                autoplay
                loop
                muted
                playsinline
                class="max-w-none"
                style:width="{naturalW}px"
                style:height="{naturalH}px"
                onloadedmetadata={handleImageLoad}
                draggable="false"
              ></video>
            {:else}
              <img
                data-lightbox-image
                bind:this={imgEl as HTMLImageElement}
                src={src}
                alt={current.title ?? ""}
                class="max-w-none pointer-events-none"
                style:width="{naturalW || "auto"}px"
                style:height="{naturalH || "auto"}px"
                onload={handleImageLoad}
                draggable="false"
              />
            {/if}
          </NsfwBlur>
        </div>
      {/if}

      <!-- Keyboard hints (desktop) -->
      <div class="hidden lg:block pointer-events-none absolute bottom-3 left-3 z-10">
        <div class="text-[0.55rem] font-mono uppercase tracking-[0.14em] text-white/25 leading-relaxed">
          <div>← → navigate · +/- zoom · 0 reset · i info · 1-5 rate · esc close</div>
        </div>
      </div>
    </div>

    {#if infoOpen && current}
      <aside class="hidden md:flex flex-col w-72 bg-black/60 backdrop-blur-md border-l border-border-subtle text-[0.78rem]">
        <div class="p-3 space-y-3 overflow-y-auto">
          {#if current.title}
            <div>
              <div class="text-kicker">Title</div>
              <p class="text-text-primary">{current.title}</p>
            </div>
          {/if}
          {#if current.width && current.height}
            <div>
              <div class="text-kicker">Dimensions</div>
              <p class="text-text-secondary font-mono">{current.width} × {current.height}</p>
            </div>
          {/if}
          {#if current.format}
            <div>
              <div class="text-kicker">Format</div>
              <p class="text-text-secondary font-mono uppercase">{current.format}</p>
            </div>
          {/if}
          {#if current.date}
            <div>
              <div class="text-kicker">Date</div>
              <p class="text-text-secondary">{current.date}</p>
            </div>
          {/if}
          {#if current.performers.length > 0}
            <div>
              <div class="text-kicker">Performers</div>
              <div class="flex flex-wrap gap-1 mt-1">
                {#each current.performers as p (p.id)}
                  <span class="tag-chip tag-chip-default">{p.name}</span>
                {/each}
              </div>
            </div>
          {/if}
          {#if current.tags.length > 0}
            <div>
              <div class="text-kicker">Tags</div>
              <div class="flex flex-wrap gap-1 mt-1">
                {#each current.tags as t (t.id)}
                  <span class="tag-chip tag-chip-default">{t.name}</span>
                {/each}
              </div>
            </div>
          {/if}
        </div>
      </aside>
    {/if}
  </div>

  <!-- Bottom bar -->
  <div class="relative z-20 border-t border-border-subtle bg-black/70 backdrop-blur-md">
    <div class="flex items-center justify-between px-3 py-1.5">
      <div class="flex items-center gap-1">
        <button
          type="button"
          onclick={goPrev}
          class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
          aria-label="Previous"
          title="Previous (←)"
        >
          <ChevronLeft class="h-4 w-4" />
        </button>
        <button
          type="button"
          onclick={goNext}
          class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
          aria-label="Next"
          title="Next (→)"
        >
          <ChevronRight class="h-4 w-4" />
        </button>
      </div>
      <div class="text-[0.7rem] font-mono text-text-muted">{counterText}</div>
      <div class="flex items-center gap-1">
        <button
          type="button"
          onclick={() => zoomBy(-0.2)}
          class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
          aria-label="Zoom out"
          title="Zoom out (-)"
        >
          <ZoomOut class="h-4 w-4" />
        </button>
        <button
          type="button"
          onclick={() => zoomBy(0.25)}
          class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
          aria-label="Zoom in"
          title="Zoom in (+)"
        >
          <ZoomIn class="h-4 w-4" />
        </button>
        <button
          type="button"
          onclick={resetTransform}
          class="p-1.5 text-text-muted hover:text-text-primary transition-colors"
          aria-label="Reset zoom"
          title="Reset (0)"
        >
          <RotateCcw class="h-4 w-4" />
        </button>
      </div>
    </div>

    {#if images.length > 1}
      <div class="border-t border-border-subtle px-2 py-1.5">
        <div class="flex gap-1 overflow-x-auto scrollbar-hidden">
          {#each images as img, i (img.id)}
            <button
              type="button"
              onclick={() => (index = i)}
              class={`flex-shrink-0 aspect-square w-12 overflow-hidden border transition-all ${
                i === index
                  ? "border-border-accent ring-1 ring-accent-500/40"
                  : "border-transparent hover:border-border-subtle opacity-60 hover:opacity-100"
              }`}
              aria-label={`Image ${i + 1}`}
            >
              <img
                src={toApiUrl(img.thumbnailPath) ?? ""}
                alt=""
                class="h-full w-full object-cover"
                loading="lazy"
              />
            </button>
          {/each}
        </div>
      </div>
    {/if}
  </div>
</div>

// apps/web/src/components/image-lightbox.tsx
"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { createPortal } from "react-dom";
import {
  X,
  ChevronLeft,
  ChevronRight,
  Info,
  Maximize,
  Play,
  Pause,
  ZoomIn,
  ZoomOut,
  Bookmark,
} from "lucide-react";
import { cn } from "@obscura/ui/lib/utils";
import { toApiUrl } from "../lib/api";
import { isVideoImage } from "../lib/image-media";
import { NsfwBlur } from "./nsfw/nsfw-gate";
import { ImageLightboxFilmstrip } from "./image-lightbox-filmstrip";
import { ImageLightboxInfo } from "./image-lightbox-info";
import type { ImageListItemDto, GalleryChapterDto } from "@obscura/contracts";

interface ImageLightboxProps {
  images: ImageListItemDto[];
  initialIndex: number;
  chapters?: GalleryChapterDto[];
  onClose: () => void;
  onImageUpdate?: (imageId: string, patch: Partial<ImageListItemDto>) => void;
  availableTags?: import("../lib/api").TagItem[];
  availablePerformers?: import("../lib/api").PerformerItem[];
}

export function ImageLightbox({
  images,
  initialIndex,
  chapters = [],
  onClose,
  onImageUpdate,
  availableTags,
  availablePerformers,
}: ImageLightboxProps) {
  const [currentIndex, setCurrentIndex] = useState(initialIndex);
  const [zoom, setZoom] = useState(1);
  const [panX, setPanX] = useState(0);
  const [panY, setPanY] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [showInfo, setShowInfo] = useState(false);
  const [slideshowActive, setSlideshowActive] = useState(false);
  const [slideshowInterval] = useState(4000);
  const [showChapters, setShowChapters] = useState(false);

  const dragStartRef = useRef({ x: 0, y: 0, panX: 0, panY: 0 });
  const containerRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  const currentImage = images[currentIndex];
  const fullUrl = currentImage ? toApiUrl(currentImage.fullPath) ?? null : null;

  // Reset zoom/pan on index change
  useEffect(() => {
    setZoom(1);
    setPanX(0);
    setPanY(0);
  }, [currentIndex]);

  // Preload adjacent images
  useEffect(() => {
    [-2, -1, 1, 2].forEach((offset) => {
      const idx = currentIndex + offset;
      if (idx >= 0 && idx < images.length) {
        const url = toApiUrl(images[idx].fullPath);
        if (url) {
          const img = new Image();
          img.src = url;
        }
      }
    });
  }, [currentIndex, images]);

  // Body scroll lock
  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, []);

  // Slideshow
  useEffect(() => {
    if (!slideshowActive) return;
    const timer = setInterval(() => {
      setCurrentIndex((i) => (i + 1) % images.length);
    }, slideshowInterval);
    return () => clearInterval(timer);
  }, [slideshowActive, slideshowInterval, images.length]);

  // Keyboard handler
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      switch (e.key) {
        case "Escape":
          onClose();
          break;
        case "ArrowLeft":
          setCurrentIndex((i) => Math.max(0, i - 1));
          break;
        case "ArrowRight":
          setCurrentIndex((i) => Math.min(images.length - 1, i + 1));
          break;
        case " ":
          e.preventDefault();
          setSlideshowActive((v) => !v);
          break;
        case "i":
        case "I":
          setShowInfo((v) => !v);
          break;
        case "f":
        case "F":
          if (!document.fullscreenElement) {
            document.documentElement.requestFullscreen?.();
          } else {
            document.exitFullscreen?.();
          }
          break;
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [onClose, images.length]);

  // Zoom helpers
  const clampZoom = useCallback((z: number) => Math.max(1, Math.min(8, z)), []);

  const handleWheel = useCallback(
    (e: React.WheelEvent) => {
      e.preventDefault();
      const newZoom = clampZoom(zoom * (1 - e.deltaY * 0.001));
      if (newZoom === 1) {
        setPanX(0);
        setPanY(0);
      }
      setZoom(newZoom);
    },
    [zoom, clampZoom]
  );

  const handleDoubleClick = useCallback(() => {
    if (zoom > 1) {
      setZoom(1);
      setPanX(0);
      setPanY(0);
    } else {
      setZoom(2.5);
    }
  }, [zoom]);

  // Pan handlers
  const handlePointerDown = useCallback(
    (e: React.PointerEvent) => {
      if (zoom <= 1) return;
      setIsDragging(true);
      dragStartRef.current = { x: e.clientX, y: e.clientY, panX, panY };
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
    },
    [zoom, panX, panY]
  );

  const handlePointerMove = useCallback(
    (e: React.PointerEvent) => {
      if (!isDragging) return;
      const dx = e.clientX - dragStartRef.current.x;
      const dy = e.clientY - dragStartRef.current.y;
      setPanX(dragStartRef.current.panX + dx);
      setPanY(dragStartRef.current.panY + dy);
    },
    [isDragging]
  );

  const handlePointerUp = useCallback(() => {
    setIsDragging(false);
  }, []);

  const goTo = useCallback(
    (index: number) => {
      setCurrentIndex(Math.max(0, Math.min(images.length - 1, index)));
    },
    [images.length]
  );

  if (!currentImage) return null;

  const content = (
    <div className="fixed inset-0 z-[100] bg-black flex flex-col select-none">
      {/* Top toolbar */}
      <div className="flex items-center justify-between px-2 sm:px-4 py-2 bg-black/50 z-10">
        <div className="flex items-center gap-2 sm:gap-3 text-white/80 text-sm min-w-0">
          <span className="text-mono-sm flex-shrink-0">
            {currentIndex + 1} / {images.length}
          </span>
          <span className="text-white/50 truncate max-w-[120px] sm:max-w-[200px] hidden sm:inline">{currentImage.title}</span>
        </div>
        <div className="flex items-center gap-0.5 sm:gap-1 flex-shrink-0">
          {/* Slideshow toggle */}
          <button
            onClick={() => setSlideshowActive((v) => !v)}
            className={cn(
              "p-2 transition-colors",
              slideshowActive ? "text-accent-500" : "text-white/60 hover:text-white"
            )}
            title="Slideshow (Space)"
          >
            {slideshowActive ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
          </button>

          {/* Chapters dropdown */}
          {chapters.length > 0 && (
            <div className="relative">
              <button
                onClick={() => setShowChapters((v) => !v)}
                className="p-2 text-white/60 hover:text-white transition-colors"
                title="Chapters"
              >
                <Bookmark className="h-4 w-4" />
              </button>
              {showChapters && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setShowChapters(false)} />
                  <div className="absolute right-0 top-full mt-1 z-50 w-48 bg-surface-2 border border-border-subtle py-1 shadow-lg">
                    {chapters.map((ch) => (
                      <button
                        key={ch.id}
                        onClick={() => {
                          goTo(ch.imageIndex - 1);
                          setShowChapters(false);
                        }}
                        className="flex items-center gap-2 w-full px-3 py-1.5 text-[0.72rem] text-text-muted hover:text-text-primary hover:bg-surface-3 text-left"
                      >
                        <span className="text-text-disabled">#{ch.imageIndex}</span>
                        <span className="truncate">{ch.title}</span>
                      </button>
                    ))}
                  </div>
                </>
              )}
            </div>
          )}

          {/* Zoom controls — hidden on mobile */}
          <button
            onClick={() => setZoom(clampZoom(zoom - 0.5))}
            className="hidden sm:flex p-2 text-white/60 hover:text-white transition-colors"
            title="Zoom out"
          >
            <ZoomOut className="h-4 w-4" />
          </button>
          <span className="hidden sm:inline text-mono-sm text-white/50 w-10 text-center">
            {Math.round(zoom * 100)}%
          </span>
          <button
            onClick={() => setZoom(clampZoom(zoom + 0.5))}
            className="hidden sm:flex p-2 text-white/60 hover:text-white transition-colors"
            title="Zoom in"
          >
            <ZoomIn className="h-4 w-4" />
          </button>

          {/* Info toggle */}
          <button
            onClick={() => setShowInfo((v) => !v)}
            className={cn(
              "p-2 transition-colors",
              showInfo ? "text-accent-500" : "text-white/60 hover:text-white"
            )}
            title="Info (I)"
          >
            <Info className="h-4 w-4" />
          </button>

          {/* Fullscreen */}
          <button
            onClick={() => {
              if (!document.fullscreenElement) {
                document.documentElement.requestFullscreen?.();
              } else {
                document.exitFullscreen?.();
              }
            }}
            className="p-2 text-white/60 hover:text-white transition-colors"
            title="Fullscreen (F)"
          >
            <Maximize className="h-4 w-4" />
          </button>

          {/* Close — always last, prominent on mobile */}
          <button
            onClick={onClose}
            className="p-2 text-white/80 hover:text-white bg-white/10 sm:bg-transparent transition-colors"
            title="Close (Esc)"
          >
            <X className="h-5 w-5 sm:h-4 sm:w-4" />
          </button>
        </div>
      </div>

      {/* Image area */}
      <div
        ref={containerRef}
        className={cn(
          "flex min-h-0 min-w-0 flex-1 items-center justify-center overflow-hidden relative",
          zoom > 1 ? (isDragging ? "cursor-grabbing" : "cursor-grab") : "cursor-zoom-in"
        )}
        onWheel={handleWheel}
        onDoubleClick={handleDoubleClick}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
        style={{ touchAction: "none" }}
      >
        {fullUrl && (
          <NsfwBlur
            isNsfw={currentImage.isNsfw ?? false}
            className="flex h-full min-h-0 min-w-0 w-full items-center justify-center"
          >
            <div className="flex h-full min-h-0 min-w-0 w-full items-center justify-center">
              {isVideoImage(currentImage) ? (
                <video
                  ref={videoRef}
                  key={currentImage.id}
                  src={fullUrl}
                  autoPlay
                  loop
                  playsInline
                  onClick={(e) => {
                    e.stopPropagation();
                    const vid = e.currentTarget;
                    if (vid.paused) {
                      vid.play();
                    } else {
                      vid.pause();
                    }
                  }}
                  className="max-h-full max-w-full object-contain cursor-pointer"
                  style={{
                    transform: `translate(${panX}px, ${panY}px) scale(${zoom})`,
                    willChange: "transform",
                    transition: isDragging ? "none" : "transform 0.15s ease-out",
                  }}
                  draggable={false}
                />
              ) : (
                <img
                  src={fullUrl}
                  alt={currentImage.title}
                  className="max-h-full max-w-full object-contain"
                  style={{
                    transform: `translate(${panX}px, ${panY}px) scale(${zoom})`,
                    willChange: "transform",
                    transition: isDragging ? "none" : "transform 0.15s ease-out",
                  }}
                  draggable={false}
                />
              )}
            </div>
          </NsfwBlur>
        )}

        {/* Nav arrows */}
        {currentIndex > 0 && (
          <button
            onClick={(e) => {
              e.stopPropagation();
              setCurrentIndex((i) => i - 1);
            }}
            className="absolute left-3 top-1/2 -translate-y-1/2 p-2 bg-black/50 text-white/70 hover:text-white hover:bg-black/70 transition-colors"
          >
            <ChevronLeft className="h-6 w-6" />
          </button>
        )}
        {currentIndex < images.length - 1 && (
          <button
            onClick={(e) => {
              e.stopPropagation();
              setCurrentIndex((i) => i + 1);
            }}
            className="absolute right-3 top-1/2 -translate-y-1/2 p-2 bg-black/50 text-white/70 hover:text-white hover:bg-black/70 transition-colors"
          >
            <ChevronRight className="h-6 w-6" />
          </button>
        )}
      </div>

      {/* Filmstrip */}
      <div className="bg-black/80 border-t border-white/10">
        <ImageLightboxFilmstrip
          images={images}
          currentIndex={currentIndex}
          onSelect={setCurrentIndex}
        />
      </div>

      {/* Info panel */}
      <ImageLightboxInfo
        image={currentImage}
        open={showInfo}
        onClose={() => setShowInfo(false)}
        onImageUpdate={onImageUpdate}
        availableTags={availableTags}
        availablePerformers={availablePerformers}
      />
    </div>
  );

  return createPortal(content, document.body);
}
