// apps/web/src/components/audio/audio-player.tsx
"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import {
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  Volume1,
  VolumeX,
  Repeat,
  Repeat1,
  Shuffle,
  Music,
} from "lucide-react";
import { cn } from "@obscura/ui/lib/utils";
import { formatDuration } from "@obscura/contracts";
import type { AudioTrackListItemDto } from "@obscura/contracts";
import { AudioWaveformFilmstrip } from "./audio-waveform-filmstrip";

export type RepeatMode = "off" | "all" | "one";

interface AudioPlayerProps {
  tracks: AudioTrackListItemDto[];
  activeTrackId: string | null;
  onTrackChange: (trackId: string) => void;
  className?: string;
  /** Resolved API URL for the parent audio library cover (album art). */
  libraryCoverUrl?: string;
}

const API_BASE =
  typeof window !== "undefined"
    ? (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000")
    : "http://localhost:4000";

function isKeyboardShortcutSuppressed(target: EventTarget | null): boolean {
  if (!(target instanceof HTMLElement)) return false;
  if (target.isContentEditable) return true;
  return Boolean(target.closest("input, textarea, select"));
}

export function AudioPlayer({
  tracks,
  activeTrackId,
  onTrackChange,
  className,
  libraryCoverUrl,
}: AudioPlayerProps) {
  const audioRef = useRef<HTMLAudioElement>(null);
  const [playing, setPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [volume, setVolume] = useState(1);
  const [muted, setMuted] = useState(false);
  const [waveformData, setWaveformData] = useState<number[] | null>(null);
  const [repeat, setRepeat] = useState<RepeatMode>("off");
  const [shuffle, setShuffle] = useState(false);
  const [timelineDragging, setTimelineDragging] = useState(false);
  const timelineDraggingRef = useRef(false);

  const activeTrack = tracks.find((t) => t.id === activeTrackId) ?? null;
  const activeIndex = activeTrack ? tracks.findIndex((t) => t.id === activeTrackId) : -1;
  const hasNext = activeIndex >= 0 && activeIndex < tracks.length - 1;
  const hasPrev = activeIndex > 0;

  // ─── Load track into audio element ────────────────────────────

  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    if (!activeTrack) {
      audio.removeAttribute("src");
      audio.load();
      setPlaying(false);
      setCurrentTime(0);
      return;
    }

    const newSrc = `${API_BASE}/audio-stream/${activeTrack.id}`;
    // Only reload if the track actually changed
    if (audio.src !== newSrc) {
      audio.src = newSrc;
      setCurrentTime(0);
      setDuration(activeTrack.duration ?? 0);
      // Attempt to play; resolves once enough data is buffered
      const playPromise = audio.play();
      if (playPromise !== undefined) {
        playPromise.catch((err) => {
          // eslint-disable-next-line no-console
          console.error("Audio play failed:", err);
        });
      }
    }
  }, [activeTrack?.id]);

  // ─── Waveform data ────────────────────────────────────────────

  useEffect(() => {
    if (!activeTrack?.waveformPath) {
      setWaveformData(null);
      return;
    }
    const url = `${API_BASE}/assets/${activeTrack.waveformPath}`;
    fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`Waveform fetch failed: ${res.status}`);
        return res.json();
      })
      .then((json) => {
        if (json.data && Array.isArray(json.data)) {
          setWaveformData(json.data);
        }
      })
      .catch((err) => {
        // eslint-disable-next-line no-console
        console.error("Failed to load waveform:", err);
        setWaveformData(null);
      });
  }, [activeTrack?.waveformPath]);

  // ─── Refs for callbacks (avoid re-registering event listeners) ─

  const activeTrackIdRef = useRef(activeTrackId);
  activeTrackIdRef.current = activeTrackId;

  const handleTrackEndRef = useRef<() => void>(() => {});
  // Set later after handleTrackEnd is defined

  // ─── Audio event listeners (registered once per mount) ────────

  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    const onTimeUpdate = () => setCurrentTime(audio.currentTime);
    const onLoadedMetadata = () => {
      if (Number.isFinite(audio.duration)) {
        setDuration(audio.duration);
      }
    };
    const onDurationChange = () => {
      if (Number.isFinite(audio.duration)) {
        setDuration(audio.duration);
      }
    };
    const onPlay = () => setPlaying(true);
    const onPause = () => setPlaying(false);
    const onEnded = () => {
      const trackId = activeTrackIdRef.current;
      if (trackId) {
        fetch(`${API_BASE}/audio-tracks/${trackId}/play`, { method: "POST" }).catch(() => {});
      }
      handleTrackEndRef.current();
    };
    const onError = () => {
      // eslint-disable-next-line no-console
      console.error("Audio element error:", audio.error);
      setPlaying(false);
    };

    audio.addEventListener("timeupdate", onTimeUpdate);
    audio.addEventListener("loadedmetadata", onLoadedMetadata);
    audio.addEventListener("durationchange", onDurationChange);
    audio.addEventListener("play", onPlay);
    audio.addEventListener("pause", onPause);
    audio.addEventListener("ended", onEnded);
    audio.addEventListener("error", onError);

    return () => {
      audio.removeEventListener("timeupdate", onTimeUpdate);
      audio.removeEventListener("loadedmetadata", onLoadedMetadata);
      audio.removeEventListener("durationchange", onDurationChange);
      audio.removeEventListener("play", onPlay);
      audio.removeEventListener("pause", onPause);
      audio.removeEventListener("ended", onEnded);
      audio.removeEventListener("error", onError);
    };
  }, []);

  // ─── Track end logic ──────────────────────────────────────────

  const handleTrackEnd = useCallback(() => {
    if (repeat === "one") {
      const audio = audioRef.current;
      if (audio) {
        audio.currentTime = 0;
        audio.play().catch(() => {});
      }
      return;
    }

    if (shuffle) {
      const otherTracks = tracks.filter((t) => t.id !== activeTrackId);
      if (otherTracks.length > 0) {
        const random = otherTracks[Math.floor(Math.random() * otherTracks.length)];
        onTrackChange(random.id);
      } else if (repeat === "all" && tracks.length > 0) {
        onTrackChange(tracks[0].id);
      }
      return;
    }

    if (activeIndex >= 0 && activeIndex < tracks.length - 1) {
      onTrackChange(tracks[activeIndex + 1].id);
    } else if (repeat === "all" && tracks.length > 0) {
      onTrackChange(tracks[0].id);
    } else {
      setPlaying(false);
    }
  }, [repeat, shuffle, activeTrackId, activeIndex, tracks, onTrackChange]);

  // Keep ref fresh for event listeners
  handleTrackEndRef.current = handleTrackEnd;

  // ─── Playback controls ────────────────────────────────────────

  const playAll = useCallback(() => {
    if (tracks.length > 0) {
      if (shuffle) {
        const random = tracks[Math.floor(Math.random() * tracks.length)];
        onTrackChange(random.id);
      } else {
        onTrackChange(tracks[0].id);
      }
    }
  }, [tracks, shuffle, onTrackChange]);

  const togglePlay = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;

    // No track loaded yet — start the first one
    if (!activeTrack) {
      playAll();
      return;
    }

    if (audio.paused) {
      const playPromise = audio.play();
      if (playPromise !== undefined) {
        playPromise.catch((err) => {
          // eslint-disable-next-line no-console
          console.error("Audio play failed:", err);
        });
      }
    } else {
      audio.pause();
    }
  }, [activeTrack, playAll]);

  const handleNext = useCallback(() => {
    if (shuffle) {
      const otherTracks = tracks.filter((t) => t.id !== activeTrackId);
      if (otherTracks.length > 0) {
        onTrackChange(otherTracks[Math.floor(Math.random() * otherTracks.length)].id);
      }
    } else if (hasNext) {
      onTrackChange(tracks[activeIndex + 1].id);
    } else if (repeat === "all" && tracks.length > 0) {
      onTrackChange(tracks[0].id);
    }
  }, [shuffle, hasNext, activeIndex, tracks, activeTrackId, repeat, onTrackChange]);

  const handlePrev = useCallback(() => {
    const audio = audioRef.current;
    if (audio && audio.currentTime > 3) {
      audio.currentTime = 0;
      return;
    }
    if (hasPrev) {
      onTrackChange(tracks[activeIndex - 1].id);
    }
  }, [hasPrev, activeIndex, tracks, onTrackChange]);

  const handleSeek = useCallback((time: number) => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.currentTime = time;
    setCurrentTime(time);
  }, []);

  const toggleMute = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.muted = !audio.muted;
    setMuted(audio.muted);
  }, []);

  const handleVolumeChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const audio = audioRef.current;
    if (!audio) return;
    const v = Number(e.target.value);
    audio.volume = v;
    setVolume(v);
    if (v > 0 && audio.muted) {
      audio.muted = false;
      setMuted(false);
    }
  }, []);

  const cycleRepeat = useCallback(() => {
    setRepeat((r) => (r === "off" ? "all" : r === "all" ? "one" : "off"));
  }, []);

  useEffect(() => {
    const seekBy = (delta: number) => {
      const audio = audioRef.current;
      if (!audio || !activeTrack) return;
      const max =
        duration > 0 && Number.isFinite(duration)
          ? duration
          : Number.isFinite(audio.duration) && audio.duration > 0
            ? audio.duration
            : Number.POSITIVE_INFINITY;
      handleSeek(Math.max(0, Math.min(max, audio.currentTime + delta)));
    };

    const handleKey = (event: KeyboardEvent) => {
      if (isKeyboardShortcutSuppressed(event.target)) return;

      switch (event.key.toLowerCase()) {
        case " ":
          event.preventDefault();
          togglePlay();
          break;
        case "k":
          if (event.metaKey || event.ctrlKey) break;
          event.preventDefault();
          togglePlay();
          break;
        case "arrowleft":
          seekBy(-5);
          break;
        case "arrowright":
          seekBy(5);
          break;
        case "j":
          seekBy(-10);
          break;
        case "l":
          seekBy(10);
          break;
        case "m":
          toggleMute();
          break;
        default:
          break;
      }
    };

    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [activeTrack, duration, handleSeek, toggleMute, togglePlay]);

  const VolumeIcon = muted || volume === 0 ? VolumeX : volume < 0.5 ? Volume1 : Volume2;
  const progress = duration > 0 ? (currentTime / duration) * 100 : 0;

  return (
    <div className={cn("surface-panel border border-border-subtle", className)}>
      <audio ref={audioRef} preload="auto" />

      {/* ─── Now playing + timeline (scene-style) + waveform film strip ─ */}
      <div className="px-4 pt-4 pb-2">
        <div className="flex items-center gap-3 mb-3">
          <div
            className={cn(
              "h-10 w-10 flex-shrink-0 overflow-hidden surface-card-sharp",
              !libraryCoverUrl && "flex items-center justify-center bg-surface-3",
            )}
          >
            {libraryCoverUrl ? (
              <img
                src={libraryCoverUrl}
                alt=""
                className="h-full w-full object-cover"
                decoding="async"
              />
            ) : (
              <Music className={cn("h-4 w-4", activeTrack ? "text-accent-500" : "text-text-disabled")} />
            )}
          </div>
          <div className="flex-1 min-w-0">
            {activeTrack ? (
              <>
                <p className="text-sm font-medium truncate text-text-primary">{activeTrack.title}</p>
                <p className="text-xs text-text-muted truncate">
                  {activeTrack.embeddedArtist ?? "Unknown artist"}
                </p>
              </>
            ) : (
              <>
                <p className="text-sm text-text-muted">No track playing</p>
                <p className="text-xs text-text-disabled">Select a track or press play</p>
              </>
            )}
          </div>
          <span className="text-xs font-mono text-text-muted tabular-nums flex-shrink-0">
            {activeTrack ? (
              <>{formatDuration(currentTime) ?? "0:00"}<span className="text-text-disabled"> / {formatDuration(duration) ?? "0:00"}</span></>
            ) : (
              "--:--"
            )}
          </span>
        </div>

        {activeTrack && duration > 0 && (
          <div
            className="video-progress-track group/track mb-2"
            data-dragging={timelineDragging}
            onPointerDown={(event) => {
              event.currentTarget.setPointerCapture(event.pointerId);
              timelineDraggingRef.current = true;
              setTimelineDragging(true);
              const rect = event.currentTarget.getBoundingClientRect();
              const nextPercent = Math.max(
                0,
                Math.min(1, (event.clientX - rect.left) / rect.width),
              );
              handleSeek(nextPercent * duration);
            }}
            onPointerMove={(event) => {
              if (!timelineDraggingRef.current) return;
              const rect = event.currentTarget.getBoundingClientRect();
              const nextPercent = Math.max(
                0,
                Math.min(1, (event.clientX - rect.left) / rect.width),
              );
              handleSeek(nextPercent * duration);
            }}
            onPointerUp={(event) => {
              event.currentTarget.releasePointerCapture(event.pointerId);
              timelineDraggingRef.current = false;
              setTimelineDragging(false);
            }}
            onPointerCancel={() => {
              timelineDraggingRef.current = false;
              setTimelineDragging(false);
            }}
            onPointerLeave={() => {
              if (!timelineDraggingRef.current) {
                setTimelineDragging(false);
              }
            }}
          >
            <div
              className="video-progress-fill"
              style={{ width: `${progress}%` }}
            />
          </div>
        )}
      </div>

      {activeTrack && waveformData && duration > 0 && (
        <div className="border-t border-border-subtle bg-black overflow-hidden">
          <AudioWaveformFilmstrip
            peaks={waveformData}
            duration={duration}
            audioRef={audioRef}
            onSeek={handleSeek}
          />
        </div>
      )}

      {/* ─── Transport controls (centered) + volume (right) ─────────── */}
      <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-x-2 px-4 py-2.5">
        <div className="min-w-0" aria-hidden />
        <div className="flex items-center justify-center gap-1">
          <button
            type="button"
            onClick={() => setShuffle((s) => !s)}
            title={shuffle ? "Shuffle: on" : "Shuffle: off"}
            className={cn(
              "p-2 transition-colors",
              shuffle ? "text-accent-500" : "text-text-disabled hover:text-text-muted",
            )}
          >
            <Shuffle className="h-3.5 w-3.5" />
          </button>

          <button
            type="button"
            onClick={handlePrev}
            disabled={!activeTrack && tracks.length === 0}
            className="p-2 text-text-muted hover:text-text-primary disabled:text-text-disabled transition-colors"
          >
            <SkipBack className="h-4 w-4" />
          </button>

          <button
            type="button"
            onClick={togglePlay}
            className={cn(
              "p-3 mx-1 transition-all",
              playing
                ? "bg-accent-500 text-bg shadow-[0_0_12px_rgba(196,154,90,0.3)]"
                : "bg-surface-3 text-text-primary hover:bg-surface-4 hover:text-accent-400",
            )}
          >
            {playing ? <Pause className="h-5 w-5" /> : <Play className="h-5 w-5 ml-0.5" />}
          </button>

          <button
            type="button"
            onClick={handleNext}
            disabled={!activeTrack && tracks.length === 0}
            className="p-2 text-text-muted hover:text-text-primary disabled:text-text-disabled transition-colors"
          >
            <SkipForward className="h-4 w-4" />
          </button>

          <button
            type="button"
            onClick={cycleRepeat}
            title={repeat === "off" ? "Repeat: off" : repeat === "all" ? "Repeat: all" : "Repeat: one"}
            className={cn(
              "p-2 transition-colors",
              repeat !== "off" ? "text-accent-500" : "text-text-disabled hover:text-text-muted",
            )}
          >
            {repeat === "one" ? <Repeat1 className="h-3.5 w-3.5" /> : <Repeat className="h-3.5 w-3.5" />}
          </button>
        </div>

        <div className="flex min-w-0 justify-end items-center gap-1.5 group/vol">
          <button
            type="button"
            onClick={toggleMute}
            className="p-1.5 text-text-disabled hover:text-text-muted transition-colors"
          >
            <VolumeIcon className="h-3.5 w-3.5" />
          </button>
          <div className="w-0 overflow-hidden group-hover/vol:w-20 transition-all duration-200">
            <input
              type="range"
              min={0}
              max={1}
              step={0.01}
              value={muted ? 0 : volume}
              onChange={handleVolumeChange}
              className="w-full h-1 accent-accent-500 cursor-pointer"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/web-svelte/src/lib/components/AudioPlayer.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    Music,
    Pause,
    Play,
    Repeat,
    Repeat1,
    Shuffle,
    SkipBack,
    SkipForward,
    Volume1,
    Volume2,
    VolumeX,
  } from "@lucide/svelte";
  import { cn } from "@obscura/ui-svelte";
  import { formatDuration, type AudioTrackListItemDto } from "@obscura/contracts";
  import { toApiUrl } from "$lib/api/core";
  import AudioWaveformFilmstrip from "./AudioWaveformFilmstrip.svelte";

  type RepeatMode = "off" | "all" | "one";

  interface Props {
    tracks: AudioTrackListItemDto[];
    activeTrackId: string | null;
    onTrackChange: (trackId: string) => void;
    class?: string;
    libraryCoverUrl?: string;
    shufflePlayKey?: number;
    onPlaybackComplete?: () => void;
    onPlayingChange?: (playing: boolean) => void;
  }

  let {
    tracks,
    activeTrackId,
    onTrackChange,
    class: className = "",
    libraryCoverUrl,
    shufflePlayKey = 0,
    onPlaybackComplete,
    onPlayingChange,
  }: Props = $props();

  let audioEl: HTMLAudioElement | null = $state(null);
  let playing = $state(false);
  let currentTime = $state(0);
  let duration = $state(0);
  let volume = $state(1);
  let muted = $state(false);
  let waveformData = $state<number[] | null>(null);
  let repeat = $state<RepeatMode>("off");
  let shuffle = $state(false);
  let timelineDragging = $state(false);

  let timelineDraggingRef = false;
  let lastShufflePlayKey = 0;

  const activeTrack = $derived(tracks.find((track) => track.id === activeTrackId) ?? null);
  const activeIndex = $derived(
    activeTrack ? tracks.findIndex((track) => track.id === activeTrackId) : -1,
  );
  const hasNext = $derived(activeIndex >= 0 && activeIndex < tracks.length - 1);
  const hasPrev = $derived(activeIndex > 0);
  const progress = $derived(duration > 0 ? (currentTime / duration) * 100 : 0);

  function isKeyboardShortcutSuppressed(target: EventTarget | null): boolean {
    if (!(target instanceof HTMLElement)) return false;
    if (target.isContentEditable) return true;
    return Boolean(target.closest("input, textarea, select"));
  }

  function requestPlay() {
    if (!audioEl) return;
    const playPromise = audioEl.play();
    if (playPromise && typeof playPromise.catch === "function") {
      void playPromise.catch((error: unknown) => {
        console.error("Audio play failed:", error);
      });
    }
  }

  function handleSeek(time: number) {
    if (!audioEl) return;
    audioEl.currentTime = time;
    currentTime = time;
  }

  function toggleMute() {
    if (!audioEl) return;
    audioEl.muted = !audioEl.muted;
    muted = audioEl.muted;
  }

  function cycleRepeat() {
    repeat = repeat === "off" ? "all" : repeat === "all" ? "one" : "off";
  }

  function playAll() {
    if (tracks.length === 0) return;
    if (shuffle) {
      const randomTrack = tracks[Math.floor(Math.random() * tracks.length)];
      onTrackChange(randomTrack!.id);
      return;
    }
    onTrackChange(tracks[0]!.id);
  }

  function togglePlay() {
    if (!audioEl) return;
    if (!activeTrack) {
      playAll();
      return;
    }
    if (audioEl.paused) requestPlay();
    else audioEl.pause();
  }

  function handleNext() {
    if (tracks.length === 0) return;
    if (shuffle) {
      const otherTracks = tracks.filter((track) => track.id !== activeTrackId);
      if (otherTracks.length > 0) {
        const randomTrack = otherTracks[Math.floor(Math.random() * otherTracks.length)];
        onTrackChange(randomTrack!.id);
      }
      return;
    }
    if (hasNext) {
      onTrackChange(tracks[activeIndex + 1]!.id);
      return;
    }
    if (repeat === "all") {
      onTrackChange(tracks[0]!.id);
    }
  }

  function handlePrev() {
    if (audioEl && audioEl.currentTime > 3) {
      audioEl.currentTime = 0;
      return;
    }
    if (hasPrev) {
      onTrackChange(tracks[activeIndex - 1]!.id);
    }
  }

  function handleTrackEnd() {
    if (repeat === "one") {
      if (audioEl) {
        audioEl.currentTime = 0;
        requestPlay();
      }
      return;
    }

    if (shuffle) {
      const otherTracks = tracks.filter((track) => track.id !== activeTrackId);
      if (otherTracks.length > 0) {
        const randomTrack = otherTracks[Math.floor(Math.random() * otherTracks.length)];
        onTrackChange(randomTrack!.id);
      } else if (repeat === "all" && tracks.length > 0) {
        onTrackChange(tracks[0]!.id);
      }
      return;
    }

    if (activeIndex >= 0 && activeIndex < tracks.length - 1) {
      onTrackChange(tracks[activeIndex + 1]!.id);
      return;
    }

    if (repeat === "all" && tracks.length > 0) {
      onTrackChange(tracks[0]!.id);
      return;
    }

    playing = false;
    onPlaybackComplete?.();
  }

  function handleVolumeInput(event: Event) {
    if (!audioEl) return;
    const nextVolume = Number((event.currentTarget as HTMLInputElement).value);
    audioEl.volume = nextVolume;
    volume = nextVolume;
    if (nextVolume > 0 && audioEl.muted) {
      audioEl.muted = false;
      muted = false;
    }
  }

  function recordTrackPlay(trackId: string) {
    const url = toApiUrl(`/audio-tracks/${trackId}/play`);
    if (!url) return;
    void fetch(url, { method: "POST" }).catch(() => {});
  }

  $effect(() => {
    if (!audioEl) return;
    if (!activeTrack) {
      audioEl.removeAttribute("src");
      audioEl.load();
      playing = false;
      currentTime = 0;
      return;
    }

    const nextSrc = toApiUrl(`/audio-stream/${activeTrack.id}`);
    if (!nextSrc || audioEl.src === nextSrc) return;
    audioEl.src = nextSrc;
    currentTime = 0;
    duration = activeTrack.duration ?? 0;
    requestPlay();
  });

  $effect(() => {
    if (!activeTrack?.waveformPath) {
      waveformData = null;
      return;
    }

    const waveformUrl = toApiUrl(
      `/assets/${activeTrack.waveformPath.replace(/^\/+/, "")}`,
    );
    if (!waveformUrl) {
      waveformData = null;
      return;
    }

    let cancelled = false;
    fetch(waveformUrl)
      .then((response) => {
        if (!response.ok) throw new Error(`Waveform fetch failed: ${response.status}`);
        return response.json() as Promise<{ data?: number[] }>;
      })
      .then((payload) => {
        if (cancelled) return;
        waveformData = Array.isArray(payload.data) ? payload.data : null;
      })
      .catch((error) => {
        if (cancelled) return;
        console.error("Failed to load waveform:", error);
        waveformData = null;
      });

    return () => {
      cancelled = true;
    };
  });

  $effect(() => {
    if (shufflePlayKey === 0 || shufflePlayKey === lastShufflePlayKey || tracks.length === 0) {
      return;
    }
    lastShufflePlayKey = shufflePlayKey;
    shuffle = true;
    const randomTrack = tracks[Math.floor(Math.random() * tracks.length)];
    if (randomTrack?.id === activeTrackId) {
      requestPlay();
    } else if (randomTrack) {
      onTrackChange(randomTrack.id);
    }
  });

  onMount(() => {
    if (!audioEl) return;

    const handleTimeUpdate = () => {
      currentTime = audioEl?.currentTime ?? 0;
    };
    const handleLoadedMetadata = () => {
      if (audioEl && Number.isFinite(audioEl.duration)) duration = audioEl.duration;
    };
    const handleDurationChange = () => {
      if (audioEl && Number.isFinite(audioEl.duration)) duration = audioEl.duration;
    };
    const handlePlay = () => {
      playing = true;
      onPlayingChange?.(true);
    };
    const handlePause = () => {
      playing = false;
      onPlayingChange?.(false);
    };
    const handleEnded = () => {
      if (activeTrackId) recordTrackPlay(activeTrackId);
      handleTrackEnd();
    };
    const handleError = () => {
      console.error("Audio element error:", audioEl?.error);
      playing = false;
      onPlayingChange?.(false);
    };

    audioEl.addEventListener("timeupdate", handleTimeUpdate);
    audioEl.addEventListener("loadedmetadata", handleLoadedMetadata);
    audioEl.addEventListener("durationchange", handleDurationChange);
    audioEl.addEventListener("play", handlePlay);
    audioEl.addEventListener("pause", handlePause);
    audioEl.addEventListener("ended", handleEnded);
    audioEl.addEventListener("error", handleError);

    return () => {
      audioEl?.removeEventListener("timeupdate", handleTimeUpdate);
      audioEl?.removeEventListener("loadedmetadata", handleLoadedMetadata);
      audioEl?.removeEventListener("durationchange", handleDurationChange);
      audioEl?.removeEventListener("play", handlePlay);
      audioEl?.removeEventListener("pause", handlePause);
      audioEl?.removeEventListener("ended", handleEnded);
      audioEl?.removeEventListener("error", handleError);
    };
  });

  function handleKeydown(event: KeyboardEvent) {
    if (isKeyboardShortcutSuppressed(event.target)) return;

    const seekBy = (delta: number) => {
      if (!audioEl || !activeTrack) return;
      const max =
        duration > 0 && Number.isFinite(duration)
          ? duration
          : Number.isFinite(audioEl.duration) && audioEl.duration > 0
            ? audioEl.duration
            : Number.POSITIVE_INFINITY;
      handleSeek(Math.max(0, Math.min(max, audioEl.currentTime + delta)));
    };

    switch (event.key.toLowerCase()) {
      case " ":
        event.preventDefault();
        togglePlay();
        break;
      case "k":
        if (event.metaKey || event.ctrlKey) break;
        event.preventDefault();
        togglePlay();
        break;
      case "arrowleft":
        seekBy(-5);
        break;
      case "arrowright":
        seekBy(5);
        break;
      case "j":
        seekBy(-10);
        break;
      case "l":
        seekBy(10);
        break;
      case "m":
        toggleMute();
        break;
    }
  }

  const VolumeIcon = $derived(
    muted || volume === 0 ? VolumeX : volume < 0.5 ? Volume1 : Volume2,
  );
</script>

<svelte:window onkeydown={handleKeydown} />

<div class={cn("surface-panel border border-border-subtle", className)}>
  <audio bind:this={audioEl} preload="auto"></audio>

  <div class="px-4 pt-4 pb-2">
    <div class="mb-3 flex items-center gap-3">
      <div class="relative flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden bg-surface-3 surface-card-sharp">
        <Music class={cn("h-4 w-4", activeTrack ? "text-accent-500" : "text-text-disabled")} />
        {#if libraryCoverUrl}
          <img
            src={libraryCoverUrl}
            alt=""
            class="absolute inset-0 h-full w-full object-cover"
            decoding="async"
            onerror={(event) => ((event.currentTarget as HTMLImageElement).style.display = "none")}
          />
        {/if}
      </div>

      <div class="min-w-0 flex-1">
        {#if activeTrack}
          <p class="truncate text-sm font-medium text-text-primary">{activeTrack.title}</p>
          <p class="truncate text-xs text-text-muted">
            {activeTrack.embeddedArtist ?? "Unknown artist"}
          </p>
        {:else}
          <p class="text-sm text-text-muted">No track playing</p>
          <p class="text-xs text-text-disabled">Select a track or press play</p>
        {/if}
      </div>

      <span class="shrink-0 font-mono tabular-nums text-xs text-text-muted">
        {#if activeTrack}
          {formatDuration(currentTime) ?? "0:00"}
          <span class="text-text-disabled"> / {formatDuration(duration) ?? "0:00"}</span>
        {:else}
          --:--
        {/if}
      </span>
    </div>

    {#if activeTrack && duration > 0}
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        class="video-progress-track group/track mb-2"
        data-dragging={timelineDragging}
        onpointerdown={(event) => {
          if (duration <= 0) return;
          timelineDraggingRef = true;
          timelineDragging = true;
          (event.currentTarget as HTMLDivElement).setPointerCapture(event.pointerId);
          const rect = (event.currentTarget as HTMLDivElement).getBoundingClientRect();
          const nextPercent = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width));
          handleSeek(nextPercent * duration);
        }}
        onpointermove={(event) => {
          if (!timelineDraggingRef || duration <= 0) return;
          const rect = (event.currentTarget as HTMLDivElement).getBoundingClientRect();
          const nextPercent = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width));
          handleSeek(nextPercent * duration);
        }}
        onpointerup={(event) => {
          (event.currentTarget as HTMLDivElement).releasePointerCapture(event.pointerId);
          timelineDraggingRef = false;
          timelineDragging = false;
        }}
        onpointercancel={() => {
          timelineDraggingRef = false;
          timelineDragging = false;
        }}
      >
        <div class="video-progress-fill" style={`width: ${progress}%`}></div>
      </div>
    {/if}
  </div>

  {#if activeTrack && waveformData && duration > 0}
    <div class="overflow-hidden border-t border-border-subtle bg-black">
      <AudioWaveformFilmstrip
        peaks={waveformData}
        {duration}
        {audioEl}
        onSeek={handleSeek}
      />
    </div>
  {/if}

  <div class="grid grid-cols-[1fr_auto_1fr] items-center gap-x-2 px-4 py-2.5">
    <div class="min-w-0" aria-hidden="true"></div>

    <div class="flex items-center justify-center gap-1">
      <button
        type="button"
        onclick={() => (shuffle = !shuffle)}
        title={shuffle ? "Shuffle: on" : "Shuffle: off"}
        class={cn(
          "p-2 transition-colors",
          shuffle ? "text-accent-500" : "text-text-disabled hover:text-text-muted",
        )}
      >
        <Shuffle class="h-3.5 w-3.5" />
      </button>

      <button
        type="button"
        onclick={handlePrev}
        disabled={!activeTrack && tracks.length === 0}
        class="p-2 text-text-muted transition-colors hover:text-text-primary disabled:text-text-disabled"
      >
        <SkipBack class="h-4 w-4" />
      </button>

      <button
        type="button"
        onclick={togglePlay}
        class={cn(
          "mx-1 p-3 transition-all",
          playing
            ? "bg-accent-500 text-bg shadow-[0_0_12px_rgba(196,154,90,0.3)]"
            : "bg-surface-3 text-text-primary hover:bg-surface-4 hover:text-accent-400",
        )}
      >
        {#if playing}
          <Pause class="h-5 w-5" />
        {:else}
          <Play class="ml-0.5 h-5 w-5" />
        {/if}
      </button>

      <button
        type="button"
        onclick={handleNext}
        disabled={!activeTrack && tracks.length === 0}
        class="p-2 text-text-muted transition-colors hover:text-text-primary disabled:text-text-disabled"
      >
        <SkipForward class="h-4 w-4" />
      </button>

      <button
        type="button"
        onclick={cycleRepeat}
        title={repeat === "off" ? "Repeat: off" : repeat === "all" ? "Repeat: all" : "Repeat: one"}
        class={cn(
          "p-2 transition-colors",
          repeat !== "off" ? "text-accent-500" : "text-text-disabled hover:text-text-muted",
        )}
      >
        {#if repeat === "one"}
          <Repeat1 class="h-3.5 w-3.5" />
        {:else}
          <Repeat class="h-3.5 w-3.5" />
        {/if}
      </button>
    </div>

    <div class="group/vol flex min-w-0 items-center justify-end gap-1.5">
      <button
        type="button"
        onclick={toggleMute}
        class="p-1.5 text-text-disabled transition-colors hover:text-text-muted"
      >
        <VolumeIcon class="h-3.5 w-3.5" />
      </button>
      <div class="w-0 overflow-hidden transition-all duration-200 group-hover/vol:w-20">
        <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={muted ? 0 : volume}
          oninput={handleVolumeInput}
          class="h-1 w-full cursor-pointer accent-accent-500"
        />
      </div>
    </div>
  </div>
</div>
