// apps/web/src/components/confirm-delete-dialog.tsx
"use client";

import { useCallback, useEffect } from "react";
import { AlertTriangle, Loader2 } from "lucide-react";
import { Button } from "@obscura/ui/primitives/button";

interface ConfirmDeleteDialogProps {
  open: boolean;
  onClose: () => void;
  entityType: "scene" | "performer" | "studio" | "tag";
  count: number;
  onDeleteFromLibrary: () => void;
  onDeleteFromDisk?: () => void;
  loading?: boolean;
}

const entityLabels: Record<string, { singular: string; plural: string }> = {
  scene: { singular: "video", plural: "videos" },
  performer: { singular: "actor", plural: "actors" },
  studio: { singular: "studio", plural: "studios" },
  tag: { singular: "tag", plural: "tags" },
};

export function ConfirmDeleteDialog({
  open,
  onClose,
  entityType,
  count,
  onDeleteFromLibrary,
  onDeleteFromDisk,
  loading,
}: ConfirmDeleteDialogProps) {
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === "Escape" && !loading) onClose();
    },
    [onClose, loading],
  );

  useEffect(() => {
    if (!open) return;
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [open, handleKeyDown]);

  if (!open) return null;

  const label = entityLabels[entityType] ?? { singular: entityType, plural: entityType + "s" };
  const noun = count === 1 ? label.singular : label.plural;
  const isScene = entityType === "scene";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/80 backdrop-blur-sm"
        onClick={loading ? undefined : onClose}
      />

      {/* Dialog */}
      <div className="relative surface-elevated border border-border-subtle w-full max-w-md mx-4 p-6 space-y-5">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 items-center justify-center bg-status-error/15 border border-status-error/30 flex-shrink-0">
            <AlertTriangle className="h-5 w-5 text-status-error" />
          </div>
          <div>
            <h3 className="text-base font-heading font-semibold text-text-primary">
              Delete {count} {noun}
            </h3>
            <p className="mt-1.5 text-[0.78rem] text-text-muted leading-relaxed">
              {isScene
                ? "This will permanently remove the selected videos from the library. Generated files (thumbnails, sprites, preview clips) will be deleted."
                : `This will permanently delete the selected ${noun}. All associations and generated files will be removed.`}
            </p>
            <p className="mt-1 text-[0.72rem] text-status-error font-medium">
              This action cannot be undone.
            </p>
          </div>
        </div>

        <div className="flex flex-col gap-2">
          {isScene ? (
            <>
              <Button
                variant="danger"
                size="md"
                className="w-full justify-center"
                onClick={onDeleteFromLibrary}
                disabled={loading}
              >
                {loading ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : null}
                Delete from library
              </Button>
              {onDeleteFromDisk && (
                <button
                  onClick={onDeleteFromDisk}
                  disabled={loading}
                  className="w-full flex items-center justify-center gap-2 px-3.5 py-2 text-sm font-medium text-status-error border border-status-error/30 bg-transparent hover:bg-status-error/10 transition-colors duration-fast disabled:opacity-40 disabled:pointer-events-none"
                >
                  {loading ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : null}
                  Delete from disk
                </button>
              )}
            </>
          ) : (
            <Button
              variant="danger"
              size="md"
              className="w-full justify-center"
              onClick={onDeleteFromLibrary}
              disabled={loading}
            >
              {loading ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : null}
              Delete {noun}
            </Button>
          )}

          <Button
            variant="ghost"
            size="md"
            className="w-full justify-center"
            onClick={onClose}
            disabled={loading}
          >
            Cancel
          </Button>
        </div>
      </div>
    </div>
  );
}

// apps/web-svelte/src/lib/components/ConfirmDeleteDialog.svelte
<script module lang="ts">
  export type DeletableEntity =
    | "video"
    | "image"
    | "audio-track"
    | "gallery"
    | "audio-library"
    | "series";
</script>

<script lang="ts">
  import { AlertTriangle, Loader2 } from "@lucide/svelte";

  interface Props {
    open: boolean;
    entityType: DeletableEntity;
    count: number;
    onClose: () => void;
    onDeleteFromLibrary: () => void | Promise<void>;
    onDeleteFromDisk?: () => void | Promise<void>;
    allowDeleteFromDisk?: boolean;
    loading?: boolean;
  }

  let {
    open,
    entityType,
    count,
    onClose,
    onDeleteFromLibrary,
    onDeleteFromDisk,
    allowDeleteFromDisk = false,
    loading = false,
  }: Props = $props();

  const labels: Record<DeletableEntity, { singular: string; plural: string }> = {
    video: { singular: "video", plural: "videos" },
    image: { singular: "image", plural: "images" },
    "audio-track": { singular: "track", plural: "tracks" },
    gallery: { singular: "gallery", plural: "galleries" },
    "audio-library": { singular: "audio library", plural: "audio libraries" },
    series: { singular: "series", plural: "series" },
  };

  const noun = $derived(count === 1 ? labels[entityType].singular : labels[entityType].plural);
  const showDiskOption = $derived(allowDeleteFromDisk && typeof onDeleteFromDisk === "function");
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <button
      type="button"
      class="absolute inset-0 bg-black/80 backdrop-blur-sm"
      onclick={() => {
        if (!loading) onClose();
      }}
      aria-label="Close delete dialog"
    ></button>

    <div
      role="dialog"
      aria-modal="true"
      aria-label={`Delete ${noun}`}
      class="relative z-10 w-full max-w-md surface-elevated p-6"
    >
      <div class="flex items-start gap-3">
        <div class="flex h-10 w-10 flex-shrink-0 items-center justify-center border border-error/30 bg-error-muted/40">
          <AlertTriangle class="h-5 w-5 text-error-text" />
        </div>
        <div class="min-w-0">
          <h2 class="text-base font-heading font-semibold text-text-primary">
            Delete {count} {noun}
          </h2>
          <p class="mt-1.5 text-[0.78rem] leading-relaxed text-text-muted">
            {#if showDiskOption}
              Remove the selected {noun} from Obscura, or remove the library entries and source
              file{count === 1 ? "" : "s"} from disk.
            {:else}
              Remove the selected {noun} from Obscura. Generated files and associations will also
              be cleaned up.
            {/if}
          </p>
          <p class="mt-1 text-[0.72rem] font-medium text-error-text">
            This action cannot be undone.
          </p>
        </div>
      </div>

      <div class="mt-5 flex flex-col gap-2">
        <button
          type="button"
          onclick={() => void onDeleteFromLibrary()}
          disabled={loading}
          aria-label="Remove from Library"
          class="inline-flex w-full items-center justify-center gap-2 bg-error-muted/60 px-3 py-2 text-sm font-medium text-error-text transition-colors hover:bg-error-muted disabled:opacity-50"
        >
          {#if loading}<Loader2 class="h-4 w-4 animate-spin" />{/if}
          Delete from Library
        </button>
        {#if showDiskOption && onDeleteFromDisk}
          <button
            type="button"
            onclick={() => void onDeleteFromDisk()}
            disabled={loading}
            class="inline-flex w-full items-center justify-center gap-2 border border-error/40 px-3 py-2 text-sm font-medium text-error-text transition-colors hover:bg-error-muted/20 disabled:opacity-50"
          >
            Delete from Library and Disk
          </button>
        {/if}
        <button
          type="button"
          onclick={onClose}
          disabled={loading}
          class="inline-flex w-full items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-text-muted transition-colors hover:bg-surface-2 hover:text-text-primary disabled:opacity-50"
        >
          Cancel
        </button>
      </div>
    </div>
  </div>
{/if}
