// apps/web/src/components/film-strip.tsx
"use client";

import { useEffect, useRef, useState, useCallback, type RefObject } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import {
  loadTrickplayFrames,
  findFrameAtTime,
  timeToTrackPosition,
  type TrickplayFrame,
} from "@obscura/ui/lib/trickplay";

interface FilmStripMarker {
  id: string;
  time: number;
  title: string;
  tag?: string;
}

interface FilmStripProps {
  spriteUrl: string;
  vttUrl: string;
  videoRef: RefObject<HTMLVideoElement | null>;
  duration: number;
  onSeek: (time: number) => void;
  markers?: FilmStripMarker[];
}

const STRIP_HEIGHT = 52;

export function FilmStrip({
  spriteUrl,
  vttUrl,
  videoRef,
  duration,
  onSeek,
  markers = [],
}: FilmStripProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const trackRef = useRef<HTMLDivElement>(null);
  const markersRef = useRef<HTMLDivElement>(null);
  const [frames, setFrames] = useState<TrickplayFrame[] | null>(null);
  const [error, setError] = useState(false);
  const draggingRef = useRef(false);
  const dragStartXRef = useRef(0);
  const dragStartTimeRef = useRef(0);
  const rafRef = useRef<number>(0);

  useEffect(() => {
    loadTrickplayFrames(vttUrl)
      .then(setFrames)
      .catch(() => setError(true));
  }, [vttUrl]);

  const frameWidth =
    frames && frames.length > 0
      ? Math.round((frames[0].width / frames[0].height) * STRIP_HEIGHT)
      : Math.round((16 / 9) * STRIP_HEIGHT);

  const spriteWidth = frames
    ? frames.reduce((max, f) => Math.max(max, f.x + f.width), 0)
    : 0;
  const spriteHeight = frames
    ? frames.reduce((max, f) => Math.max(max, f.y + f.height), 0)
    : 0;

  const trackWidth = frames ? frames.length * frameWidth : 0;

  // Apply track position for a given time — playhead stays at viewport center
  const applyPosition = useCallback(
    (time: number) => {
      const container = containerRef.current;
      const track = trackRef.current;
      if (!container || !track || !frames) return;

      const containerWidth = container.clientWidth;
      const trackPosition = timeToTrackPosition(frames, time, frameWidth);
      const tx = containerWidth / 2 - trackPosition;

      const transform = `translateX(${tx}px)`;
      track.style.transform = transform;
      if (markersRef.current) markersRef.current.style.transform = transform;
    },
    [frames, frameWidth]
  );

  // rAF loop: read video.currentTime every frame and set transform directly
  useEffect(() => {
    if (!frames || frames.length === 0) return;

    const tick = () => {
      const video = videoRef.current;
      if (!video || !containerRef.current || !trackRef.current || draggingRef.current) {
        rafRef.current = requestAnimationFrame(tick);
        return;
      }

      applyPosition(video.currentTime);
      rafRef.current = requestAnimationFrame(tick);
    };

    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [frames, frameWidth, videoRef, applyPosition]);

  const handlePointerDown = useCallback(
    (e: React.PointerEvent) => {
      if (!frames) return;
      draggingRef.current = true;
      dragStartXRef.current = e.clientX;
      dragStartTimeRef.current = videoRef.current?.currentTime ?? 0;
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
    },
    [frames, videoRef]
  );

  const handlePointerMove = useCallback(
    (e: React.PointerEvent) => {
      if (!draggingRef.current || !frames) return;
      const dx = e.clientX - dragStartXRef.current;
      const pixelsPerSecond = trackWidth / duration;
      const timeDelta = -dx / pixelsPerSecond;
      const newTime = Math.max(
        0,
        Math.min(duration, dragStartTimeRef.current + timeDelta)
      );
      applyPosition(newTime);
      onSeek(newTime);
    },
    [frames, trackWidth, duration, onSeek, applyPosition]
  );

  const handlePointerUp = useCallback(() => {
    draggingRef.current = false;
  }, []);

  const jumpFrame = useCallback(
    (direction: -1 | 1) => {
      if (!frames || frames.length === 0) return;
      const time = videoRef.current?.currentTime ?? 0;
      const currentIndex = findFrameAtTime(frames, time);
      const nextIndex = Math.max(
        0,
        Math.min(frames.length - 1, currentIndex + direction)
      );
      onSeek(frames[nextIndex].start);
    },
    [frames, videoRef, onSeek]
  );

  if (error || !frames || frames.length === 0) {
    return null;
  }

  return (
    <div className="relative flex items-center" style={{ height: STRIP_HEIGHT }}>
      <button
        type="button"
        onClick={() => jumpFrame(-1)}
        className="relative z-30 flex h-full w-8 flex-shrink-0 items-center justify-center bg-black/80 text-white/50 transition-colors hover:text-white"
      >
        <ChevronLeft className="h-4 w-4" />
      </button>

      <div
        ref={containerRef}
        className="relative flex-1 overflow-hidden select-none touch-none"
        style={{ height: STRIP_HEIGHT }}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
      >
        <div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-16 bg-gradient-to-r from-black/60 to-transparent" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-16 bg-gradient-to-l from-black/60 to-transparent" />

        <div className="pointer-events-none absolute inset-y-0 left-1/2 z-20 -translate-x-1/2">
          <div className="absolute -top-px left-1/2 -translate-x-1/2 border-x-[5px] border-t-[5px] border-x-transparent border-t-accent-500" />
          <div className="h-full w-[2px] bg-accent-500 shadow-[0_0_8px_rgba(var(--accent-500-rgb,59,130,246),0.6)]" />
          <div className="absolute -bottom-px left-1/2 -translate-x-1/2 border-x-[5px] border-b-[5px] border-x-transparent border-b-accent-500" />
        </div>

        <div
          ref={trackRef}
          className="absolute inset-y-0 flex will-change-transform"
          style={{
            width: trackWidth,
            cursor: draggingRef.current ? "grabbing" : "grab",
          }}
        >
          {frames.map((frame, i) => (
            <div
              key={i}
              className="flex-shrink-0"
              style={{
                width: frameWidth,
                height: STRIP_HEIGHT,
              }}
            >
              <div
                className="h-full w-full"
                style={{
                  backgroundImage: `url(${spriteUrl})`,
                  backgroundSize: `${(spriteWidth / frame.width) * frameWidth}px ${(spriteHeight / frame.height) * STRIP_HEIGHT}px`,
                  backgroundPosition: `-${(frame.x / frame.width) * frameWidth}px -${(frame.y / frame.height) * STRIP_HEIGHT}px`,
                  backgroundRepeat: "no-repeat",
                }}
              />
            </div>
          ))}

        </div>

        {/* Marker indicators — same width, synced via rAF in markersRef */}
        {duration > 0 && markers.length > 0 && (
          <div
            ref={markersRef}
            className="absolute inset-y-0 pointer-events-none will-change-transform"
            style={{ width: trackWidth }}
          >
            {markers.map((marker) => {
              const left = timeToTrackPosition(frames, marker.time, frameWidth);
              return (
                <div
                  key={marker.id}
                  className="absolute top-0 bottom-0 flex flex-col items-center"
                  style={{ left }}
                >
                  <div className="w-px h-full bg-accent-500/50" />
                  <div className="absolute bottom-0.5 left-1/2 -translate-x-1/2 whitespace-nowrap px-1.5 py-px text-[0.5rem] font-medium tracking-wide uppercase leading-tight bg-black/80 text-accent-300 border border-accent-500/30 ">
                    {marker.title}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      <button
        type="button"
        onClick={() => jumpFrame(1)}
        className="relative z-30 flex h-full w-8 flex-shrink-0 items-center justify-center bg-black/80 text-white/50 transition-colors hover:text-white"
      >
        <ChevronRight className="h-4 w-4" />
      </button>
    </div>
  );
}

// apps/web-svelte/src/lib/components/FilmStrip.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { ChevronLeft, ChevronRight } from "@lucide/svelte";
  import {
    loadTrickplayFrames,
    findFrameAtTime,
    timeToTrackPosition,
    type TrickplayFrame,
  } from "@obscura/ui-svelte";

  interface FilmStripMarker {
    id: string;
    time: number;
    title: string;
    tag?: string;
  }

  interface Props {
    spriteUrl: string;
    vttUrl: string;
    videoEl: HTMLVideoElement | null | undefined;
    duration: number;
    onSeek: (time: number) => void;
    markers?: FilmStripMarker[];
    onStripInteractionChange?: (active: boolean) => void;
  }

  let {
    spriteUrl,
    vttUrl,
    videoEl,
    duration,
    onSeek,
    markers = [],
    onStripInteractionChange,
  }: Props = $props();

  const STRIP_HEIGHT = 52;
  const DESKTOP_WHEEL_SCRUB_MQ = "(pointer: fine) and (hover: hover)";

  let containerEl: HTMLDivElement | undefined = $state();
  let trackEl: HTMLDivElement | undefined = $state();
  let markersEl: HTMLDivElement | undefined = $state();
  let frames = $state<TrickplayFrame[] | null>(null);
  let error = $state(false);
  let dragging = false;
  let dragStartX = 0;
  let dragStartTime = 0;
  let rafId = 0;
  let wheelIdleTimer: number | null = null;

  const frameWidth = $derived(
    frames && frames.length > 0
      ? Math.round((frames[0].width / frames[0].height) * STRIP_HEIGHT)
      : Math.round((16 / 9) * STRIP_HEIGHT),
  );
  const spriteWidth = $derived(
    frames ? frames.reduce((m, f) => Math.max(m, f.x + f.width), 0) : 0,
  );
  const spriteHeight = $derived(
    frames ? frames.reduce((m, f) => Math.max(m, f.y + f.height), 0) : 0,
  );
  const trackWidth = $derived(frames ? frames.length * frameWidth : 0);

  function clearWheelIdleTimer() {
    if (wheelIdleTimer != null) {
      window.clearTimeout(wheelIdleTimer);
      wheelIdleTimer = null;
    }
  }

  function notifyWheelScrubActivity() {
    onStripInteractionChange?.(true);
    clearWheelIdleTimer();
    wheelIdleTimer = window.setTimeout(() => {
      wheelIdleTimer = null;
      onStripInteractionChange?.(false);
    }, 320);
  }

  function applyPosition(time: number) {
    if (!containerEl || !trackEl || !frames) return;
    const containerWidth = containerEl.clientWidth;
    const trackPosition = timeToTrackPosition(frames, time, frameWidth);
    const tx = containerWidth / 2 - trackPosition;
    const transform = `translateX(${tx}px)`;
    trackEl.style.transform = transform;
    if (markersEl) markersEl.style.transform = transform;
  }

  $effect(() => {
    loadTrickplayFrames(vttUrl)
      .then((f) => (frames = f))
      .catch(() => (error = true));
  });

  $effect(() => {
    if (!frames || frames.length === 0) return;
    const tick = () => {
      if (!videoEl || !containerEl || !trackEl || dragging) {
        rafId = requestAnimationFrame(tick);
        return;
      }
      applyPosition(videoEl.currentTime);
      rafId = requestAnimationFrame(tick);
    };
    rafId = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafId);
  });

  $effect(() => {
    if (!frames || frames.length === 0 || duration <= 0 || trackWidth <= 0) return;
    const el = containerEl;
    if (!el) return;

    const mq = window.matchMedia(DESKTOP_WHEEL_SCRUB_MQ);

    const onWheel = (e: WheelEvent) => {
      if (!mq.matches) return;
      const raw = Math.abs(e.deltaX) > Math.abs(e.deltaY) ? e.deltaX : e.deltaY;
      if (raw === 0) return;
      e.preventDefault();
      e.stopPropagation();
      const pixelsPerSecond = trackWidth / duration;
      const timeDelta = raw / pixelsPerSecond;
      const current = videoEl?.currentTime ?? 0;
      const newTime = Math.max(0, Math.min(duration, current + timeDelta));
      applyPosition(newTime);
      onSeek(newTime);
      notifyWheelScrubActivity();
    };

    const syncListener = () => {
      el.removeEventListener("wheel", onWheel);
      if (mq.matches) el.addEventListener("wheel", onWheel, { passive: false });
    };

    syncListener();
    mq.addEventListener("change", syncListener);
    return () => {
      mq.removeEventListener("change", syncListener);
      el.removeEventListener("wheel", onWheel);
    };
  });

  onMount(() => {
    return () => {
      clearWheelIdleTimer();
      onStripInteractionChange?.(false);
    };
  });

  function handlePointerDown(e: PointerEvent) {
    if (!frames) return;
    clearWheelIdleTimer();
    onStripInteractionChange?.(true);
    dragging = true;
    dragStartX = e.clientX;
    dragStartTime = videoEl?.currentTime ?? 0;
    (e.target as HTMLElement).setPointerCapture(e.pointerId);
  }

  function handlePointerMove(e: PointerEvent) {
    if (!dragging || !frames) return;
    const dx = e.clientX - dragStartX;
    const pixelsPerSecond = trackWidth / duration;
    const timeDelta = -dx / pixelsPerSecond;
    const newTime = Math.max(0, Math.min(duration, dragStartTime + timeDelta));
    applyPosition(newTime);
    onSeek(newTime);
  }

  function endPointer() {
    dragging = false;
    clearWheelIdleTimer();
    onStripInteractionChange?.(false);
  }

  function jumpFrame(direction: -1 | 1) {
    if (!frames || frames.length === 0) return;
    const time = videoEl?.currentTime ?? 0;
    const currentIndex = findFrameAtTime(frames, time);
    const nextIndex = Math.max(0, Math.min(frames.length - 1, currentIndex + direction));
    onSeek(frames[nextIndex].start);
  }
</script>

{#if frames && frames.length > 0 && !error}
  <div class="relative flex items-center" style:height="{STRIP_HEIGHT}px">
    <button
      type="button"
      onclick={() => jumpFrame(-1)}
      class="relative z-30 flex h-full w-8 flex-shrink-0 items-center justify-center bg-black/80 text-white/50 transition-colors hover:text-white"
      aria-label="Previous frame"
    >
      <ChevronLeft class="h-4 w-4" />
    </button>

    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      bind:this={containerEl}
      class="relative flex-1 overflow-hidden select-none touch-none"
      style:height="{STRIP_HEIGHT}px"
      onpointerdown={handlePointerDown}
      onpointermove={handlePointerMove}
      onpointerup={endPointer}
      onpointercancel={endPointer}
    >
      <div class="pointer-events-none absolute inset-y-0 left-0 z-10 w-16 bg-gradient-to-r from-black/60 to-transparent"></div>
      <div class="pointer-events-none absolute inset-y-0 right-0 z-10 w-16 bg-gradient-to-l from-black/60 to-transparent"></div>

      <div class="pointer-events-none absolute inset-y-0 left-1/2 z-20 -translate-x-1/2">
        <div class="absolute -top-px left-1/2 -translate-x-1/2 border-x-[5px] border-t-[5px] border-x-transparent border-t-accent-500"></div>
        <div class="h-full w-[2px] bg-accent-500 shadow-[0_0_8px_rgba(var(--accent-500-rgb,59,130,246),0.6)]"></div>
        <div class="absolute -bottom-px left-1/2 -translate-x-1/2 border-x-[5px] border-b-[5px] border-x-transparent border-b-accent-500"></div>
      </div>

      <div
        bind:this={trackEl}
        class="absolute inset-y-0 flex will-change-transform"
        style:width="{trackWidth}px"
        style:cursor={dragging ? "grabbing" : "grab"}
      >
        {#each frames as frame, i (i)}
          <div class="flex-shrink-0" style:width="{frameWidth}px" style:height="{STRIP_HEIGHT}px">
            <div
              class="h-full w-full"
              style:background-image="url({spriteUrl})"
              style:background-size="{(spriteWidth / frame.width) * frameWidth}px {(spriteHeight / frame.height) * STRIP_HEIGHT}px"
              style:background-position="-{(frame.x / frame.width) * frameWidth}px -{(frame.y / frame.height) * STRIP_HEIGHT}px"
              style:background-repeat="no-repeat"
            ></div>
          </div>
        {/each}
      </div>

      {#if duration > 0 && markers.length > 0}
        <div
          bind:this={markersEl}
          class="absolute inset-y-0 pointer-events-none will-change-transform"
          style:width="{trackWidth}px"
        >
          {#each markers as marker (marker.id)}
            {@const left = timeToTrackPosition(frames, marker.time, frameWidth)}
            <div class="absolute top-0 bottom-0 flex flex-col items-center" style:left="{left}px">
              <div class="w-px h-full bg-accent-500/50"></div>
              <div class="absolute bottom-0.5 left-1/2 -translate-x-1/2 whitespace-nowrap px-1.5 py-px text-[0.5rem] font-medium tracking-wide uppercase leading-tight bg-black/80 text-accent-300 border border-accent-500/30">
                {marker.title}
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    <button
      type="button"
      onclick={() => jumpFrame(1)}
      class="relative z-30 flex h-full w-8 flex-shrink-0 items-center justify-center bg-black/80 text-white/50 transition-colors hover:text-white"
      aria-label="Next frame"
    >
      <ChevronRight class="h-4 w-4" />
    </button>
  </div>
{/if}
