// apps/web/src/components/shared/star-rating-picker.tsx
"use client";

import { useState } from "react";
import { Star } from "lucide-react";
import { cn } from "@obscura/ui/lib/utils";

export interface StarRatingPickerProps {
  value: number | null;
  onChange?: (value: number | null) => void;
  readOnly?: boolean;
}

export function StarRatingPicker({
  value,
  onChange,
  readOnly,
}: StarRatingPickerProps) {
  const stars = value ? Math.round(value / 20) : 0;
  const [hovered, setHovered] = useState(0);

  if (readOnly) {
    return (
      <div className="flex items-center gap-0.5">
        {Array.from({ length: 5 }).map((_, i) => (
          <Star
            key={i}
            className={cn(
              "h-4 w-4",
              i < stars
                ? "fill-accent-500 text-accent-500"
                : "text-text-disabled"
            )}
          />
        ))}
      </div>
    );
  }

  return (
    <div
      className="star-rating-picker"
      onMouseLeave={() => setHovered(0)}
    >
      {Array.from({ length: 5 }).map((_, i) => {
        const starIdx = i + 1;
        const active = hovered > 0 ? starIdx <= hovered : starIdx <= stars;
        return (
          <button
            key={i}
            type="button"
            onMouseEnter={() => setHovered(starIdx)}
            onClick={() => {
              const newVal = starIdx === stars ? null : starIdx * 20;
              onChange?.(newVal);
            }}
          >
            <Star
              className={cn(
                "h-5 w-5 transition-colors duration-fast",
                active
                  ? "fill-accent-500 text-accent-500"
                  : "text-text-disabled hover:text-accent-800"
              )}
            />
          </button>
        );
      })}
    </div>
  );
}

// apps/web-svelte/src/lib/components/StarRatingPicker.svelte
<script lang="ts">
  import { Star } from "@lucide/svelte";
  import { cn } from "@obscura/ui-svelte";

  interface Props {
    value: number | null;
    onChange?: (value: number | null) => void;
    readOnly?: boolean;
  }

  let { value, onChange, readOnly = false }: Props = $props();

  const stars = $derived(value ? Math.round(value / 20) : 0);
  let hovered = $state(0);
</script>

{#if readOnly}
  <div class="flex items-center gap-0.5">
    {#each Array.from({ length: 5 }) as _, i}
      <Star
        class={cn(
          "h-4 w-4",
          i < stars ? "fill-accent-500 text-accent-500" : "text-text-disabled",
        )}
      />
    {/each}
  </div>
{:else}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="flex items-center gap-0.5" onmouseleave={() => (hovered = 0)}>
    {#each Array.from({ length: 5 }) as _, i}
      {@const starIdx = i + 1}
      {@const active = hovered > 0 ? starIdx <= hovered : starIdx <= stars}
      <button
        type="button"
        onmouseenter={() => (hovered = starIdx)}
        onclick={() => {
          const newVal = starIdx === stars ? null : starIdx * 20;
          onChange?.(newVal);
        }}
      >
        <Star
          class={cn(
            "h-5 w-5 transition-colors duration-fast",
            active ? "fill-accent-500 text-accent-500" : "text-text-disabled hover:text-accent-800",
          )}
        />
      </button>
    {/each}
  </div>
{/if}
