// apps/web/src/components/upload/upload-drop-zone.tsx
"use client";

import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from "react";
import { UploadCloud, Check, AlertCircle, Loader2 } from "lucide-react";
import { useUploader } from "./use-uploader";
import {
  acceptForCategory,
  categoryForTarget,
  type UploadTarget,
} from "./upload-types";
import { LibraryRootPicker } from "./library-root-picker";

interface UploadDropZoneProps {
  target: UploadTarget;
  onUploaded?: () => void;
  children: ReactNode;
  /** Optional className for the drop surface wrapper. */
  className?: string;
  /** Label shown in the drop overlay. Defaults to a category-aware string. */
  dropLabel?: string;
  /**
   * When false, the drop zone passes drag events through but renders no
   * overlay and does not accept drops. Used to disable uploads on views
   * that do not have a resolvable context (e.g. top-level audio list).
   */
  enabled?: boolean;
}

/**
 * Wraps a list/grid with drag-and-drop file upload support. Renders an
 * absolutely-positioned "Drop to add" overlay while a drag is active
 * over the wrapper, and a status strip at the bottom of the wrapper
 * during and after upload.
 */
export function UploadDropZone({
  target,
  onUploaded,
  children,
  className,
  dropLabel,
  enabled = true,
}: UploadDropZoneProps) {
  const uploader = useUploader({ target, onUploaded });
  const [isDragging, setIsDragging] = useState(false);
  const dragDepthRef = useRef(0);
  const category = categoryForTarget(target);
  const accept = acceptForCategory(category);

  const handleDragEnter = useCallback(
    (e: React.DragEvent) => {
      if (!enabled) return;
      if (!e.dataTransfer?.types.includes("Files")) return;
      e.preventDefault();
      dragDepthRef.current += 1;
      setIsDragging(true);
    },
    [enabled],
  );

  const handleDragOver = useCallback(
    (e: React.DragEvent) => {
      if (!enabled) return;
      if (!e.dataTransfer?.types.includes("Files")) return;
      e.preventDefault();
      if (e.dataTransfer) {
        e.dataTransfer.dropEffect = "copy";
      }
    },
    [enabled],
  );

  const handleDragLeave = useCallback(
    (e: React.DragEvent) => {
      if (!enabled) return;
      e.preventDefault();
      dragDepthRef.current = Math.max(0, dragDepthRef.current - 1);
      if (dragDepthRef.current === 0) {
        setIsDragging(false);
      }
    },
    [enabled],
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      if (!enabled) return;
      e.preventDefault();
      dragDepthRef.current = 0;
      setIsDragging(false);
      const dropped = e.dataTransfer?.files;
      if (!dropped || dropped.length === 0) return;
      void uploader.uploadFiles(dropped);
    },
    [enabled, uploader],
  );

  // Reset drag state if the user drops outside the window.
  useEffect(() => {
    const onDragEndGlobal = () => {
      dragDepthRef.current = 0;
      setIsDragging(false);
    };
    window.addEventListener("dragend", onDragEndGlobal);
    window.addEventListener("drop", onDragEndGlobal);
    return () => {
      window.removeEventListener("dragend", onDragEndGlobal);
      window.removeEventListener("drop", onDragEndGlobal);
    };
  }, []);

  const total = uploader.files.length;
  const done = uploader.files.filter((f) => f.status === "done").length;
  const failed = uploader.files.filter((f) => f.status === "error").length;
  const showStatusStrip = total > 0;
  const errors = uploader.files.filter((f) => f.status === "error");

  return (
    <div
      className={className ?? "relative"}
      onDragEnter={handleDragEnter}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      {children}

      {isDragging && enabled ? (
        <div className="pointer-events-none absolute inset-0 z-40 flex items-center justify-center bg-bg/80 backdrop-blur-sm">
          <div className="flex flex-col items-center gap-3 border border-accent-500/50 bg-surface-1/90 px-10 py-8 shadow-[0_0_48px_rgba(199,155,92,0.25)]">
            <UploadCloud className="h-10 w-10 text-accent-400" />
            <div className="text-sm font-medium text-text-primary">
              {dropLabel ?? `Drop ${category} files to import`}
            </div>
            <div className="text-[0.7rem] text-text-muted font-mono">
              {accept}
            </div>
          </div>
        </div>
      ) : null}

      {showStatusStrip ? (
        <div className="pointer-events-auto fixed bottom-4 right-4 z-40 w-[340px] border border-border-subtle bg-surface-2/95 backdrop-blur-md shadow-lg">
          <div className="flex items-center justify-between border-b border-border-subtle px-3 py-2">
            <div className="flex items-center gap-2 text-[0.78rem] font-medium text-text-primary">
              {uploader.isUploading ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin text-accent-400" />
              ) : failed > 0 ? (
                <AlertCircle className="h-3.5 w-3.5 text-status-error" />
              ) : (
                <Check className="h-3.5 w-3.5 text-status-success" />
              )}
              <span>
                {uploader.isUploading
                  ? `Uploading ${done + 1} of ${total}`
                  : failed > 0
                    ? `Uploaded ${done} of ${total} (${failed} failed)`
                    : `Uploaded ${done} of ${total}`}
              </span>
            </div>
            <button
              onClick={uploader.resetState}
              className="text-[0.7rem] text-text-muted hover:text-text-primary"
              disabled={uploader.isUploading}
            >
              Dismiss
            </button>
          </div>
          {errors.length > 0 ? (
            <div className="max-h-40 overflow-y-auto px-3 py-2 space-y-1">
              {errors.map((entry, i) => (
                <div key={i} className="text-[0.68rem] text-status-error">
                  <span className="font-mono">{entry.file.name}</span> —{" "}
                  {entry.error}
                </div>
              ))}
            </div>
          ) : null}
        </div>
      ) : null}

      <LibraryRootPicker
        open={uploader.needsRootPicker}
        roots={uploader.candidateRoots}
        onConfirm={uploader.confirmRootPick}
        onCancel={uploader.cancelRootPick}
      />
    </div>
  );
}

// apps/web-svelte/src/lib/components/UploadDropZone.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { AlertCircle, Check, Loader2, UploadCloud } from "@lucide/svelte";
  import DestinationPicker from "$lib/components/DestinationPicker.svelte";
  import LibraryRootPicker from "$lib/components/LibraryRootPicker.svelte";
  import { createUploader } from "$lib/upload/uploader.svelte";
  import {
    acceptForCategory,
    categoryForTarget,
    dragHasFiles,
    uploadTargetLabel,
    type UploadTarget,
  } from "$lib/upload/upload-types";

  interface Props {
    target: UploadTarget;
    onUploaded?: () => void | Promise<void>;
    enabled?: boolean;
    dropLabel?: string;
    class?: string;
    children?: Snippet;
  }

  let {
    target,
    onUploaded,
    enabled = true,
    dropLabel,
    class: className = "relative",
    children,
  }: Props = $props();

  // svelte-ignore state_referenced_locally
  const uploader = createUploader({ target, onUploaded });
  const category = $derived(categoryForTarget(target));
  const accept = $derived(acceptForCategory(category));
  let isDragging = $state(false);
  let dragDepth = 0;

  const total = $derived(uploader.files.length);
  const done = $derived(uploader.files.filter((f) => f.status === "done").length);
  const failed = $derived(uploader.files.filter((f) => f.status === "error").length);
  const errors = $derived(uploader.files.filter((f) => f.status === "error"));

  function onDragEnter(event: DragEvent) {
    if (!enabled || !dragHasFiles(event.dataTransfer)) return;
    event.preventDefault();
    event.stopPropagation();
    dragDepth += 1;
    isDragging = true;
  }

  function onDragOver(event: DragEvent) {
    if (!enabled || !dragHasFiles(event.dataTransfer)) return;
    event.preventDefault();
    if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";
  }

  function onDragLeave() {
    if (!enabled) return;
    dragDepth = Math.max(0, dragDepth - 1);
    if (dragDepth === 0) isDragging = false;
  }

  function onDrop(event: DragEvent) {
    if (!enabled) return;
    event.preventDefault();
    event.stopPropagation();
    dragDepth = 0;
    isDragging = false;
    const files = event.dataTransfer?.files;
    if (files?.length) void uploader.uploadFiles(files);
  }
</script>

<svelte:window
  ondragover={(event) => {
    if (enabled && dragHasFiles(event.dataTransfer)) event.preventDefault();
  }}
  ondrop={(event) => {
    if (enabled && dragHasFiles(event.dataTransfer)) event.preventDefault();
    dragDepth = 0;
    isDragging = false;
  }}
  ondragend={() => {
    dragDepth = 0;
    isDragging = false;
  }}
/>

<div
  class={className}
  role="region"
  aria-label="File upload drop zone"
  ondragenter={onDragEnter}
  ondragover={onDragOver}
  ondragleave={onDragLeave}
  ondrop={onDrop}
>
  {#if children}{@render children()}{/if}

  {#if isDragging && enabled}
    <div class="pointer-events-none absolute inset-0 z-40 flex items-center justify-center bg-bg/80 backdrop-blur-sm">
      <div class="flex flex-col items-center gap-3 border border-border-accent bg-surface-1/95 px-10 py-8 shadow-[var(--shadow-glow-accent-strong)]">
        <UploadCloud class="h-10 w-10 text-text-accent" />
        <div class="text-sm font-medium text-text-primary">
          {dropLabel ?? `Drop ${uploadTargetLabel(target)} to import`}
        </div>
        <div class="font-mono text-[0.7rem] text-text-muted">{accept}</div>
      </div>
    </div>
  {/if}

  {#if total > 0}
    <div class="fixed bottom-4 right-4 z-40 w-[min(340px,calc(100vw-2rem))] border border-border-subtle bg-surface-2/95 shadow-lg backdrop-blur-md">
      <div class="flex items-center justify-between gap-3 border-b border-border-subtle px-3 py-2">
        <div class="flex min-w-0 items-center gap-2 text-[0.78rem] font-medium text-text-primary">
          {#if uploader.isUploading}
            <Loader2 class="h-3.5 w-3.5 flex-shrink-0 animate-spin text-text-accent" />
          {:else if failed > 0}
            <AlertCircle class="h-3.5 w-3.5 flex-shrink-0 text-error-text" />
          {:else}
            <Check class="h-3.5 w-3.5 flex-shrink-0 text-success-text" />
          {/if}
          <span class="truncate">
            {uploader.isUploading
              ? `Uploading ${Math.min(done + 1, total)} of ${total}`
              : failed > 0
                ? `Uploaded ${done} of ${total} (${failed} failed)`
                : `Uploaded ${done} of ${total}`}
          </span>
        </div>
        <button
          type="button"
          onclick={uploader.resetState}
          disabled={uploader.isUploading}
          class="text-[0.7rem] text-text-muted hover:text-text-primary disabled:opacity-50"
        >
          Dismiss
        </button>
      </div>
      {#if errors.length > 0}
        <div class="max-h-40 space-y-1 overflow-y-auto px-3 py-2">
          {#each errors as entry, i (`${entry.file.name}-${i}`)}
            <div class="text-[0.68rem] text-error-text">
              <span class="font-mono">{entry.file.name}</span>: {entry.error}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  {/if}

  <LibraryRootPicker
    open={uploader.needsRootPicker}
    roots={uploader.candidateRoots}
    onConfirm={uploader.confirmRootPick}
    onCancel={uploader.cancelRootPick}
  />
  <DestinationPicker
    open={uploader.needsGalleryPicker}
    title="Choose a gallery"
    description="Pick the folder-backed gallery these image files should land in."
    items={uploader.candidateGalleries.map((gallery) => ({
      id: gallery.id,
      title: gallery.title,
      subtitle: `${gallery.imageCount} image${gallery.imageCount === 1 ? "" : "s"}`,
    }))}
    onConfirm={uploader.confirmGalleryPick}
    onCancel={uploader.cancelGalleryPick}
  />
  <DestinationPicker
    open={uploader.needsAudioLibraryPicker}
    title="Choose an audio library"
    description="Pick the library these tracks should land in."
    items={uploader.candidateAudioLibraries.map((library) => ({
      id: library.id,
      title: library.title,
      subtitle: `${library.trackCount} track${library.trackCount === 1 ? "" : "s"}`,
    }))}
    onConfirm={uploader.confirmAudioLibraryPick}
    onCancel={uploader.cancelAudioLibraryPick}
  />
</div>
