// apps/web-svelte/src/lib/components/CommandPalette.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { browser } from "$app/environment";
  import { Search, X, Clock, ArrowRight, Trash2 } from "@lucide/svelte";
  import { cn, dur, ease, flyDown } from "@obscura/ui-svelte";
  import { fade } from "svelte/transition";
  import type { SearchResponseDto } from "@obscura/contracts";
  import SearchResultCard from "$lib/components/SearchResultCard.svelte";
  import { useSearch } from "$lib/stores/search.svelte";
  import { useNsfw } from "$lib/nsfw/store.svelte";
  import { entityTerms } from "$lib/terminology";
  import { fetchSearch } from "$lib/v1/api/media-v1";
  import { recentSearches } from "$lib/stores/recent-searches.svelte";
  import { buildHrefWithFrom } from "$lib/back-navigation";

  const search = useSearch();
  const nsfw = useNsfw();
  const recent = recentSearches();

  let query = $state("");
  let results = $state<SearchResponseDto | null>(null);
  let loading = $state(false);
  let inputRef = $state<HTMLInputElement | null>(null);

  let activeRequest = 0;
  const currentPath = $derived(`${page.url.pathname}${page.url.search}`);
  const open = $derived(search.open);
  const hasQuery = $derived(query.trim().length >= 2);
  const hasResults = $derived(
    results != null && results.groups.some((group) => group.items.length > 0),
  );

  function closePalette() {
    search.closePalette();
  }

  function clearQuery() {
    query = "";
    results = null;
    loading = false;
  }

  async function runSearch(term: string) {
    const trimmed = term.trim();
    const requestId = ++activeRequest;

    if (trimmed.length < 2) {
      results = null;
      loading = false;
      return;
    }

    loading = true;
    try {
      const data = await fetchSearch({
        q: trimmed,
        limit: 6,
        nsfw: nsfw.mode,
      });
      if (requestId === activeRequest) {
        results = data;
      }
    } catch {
      if (requestId === activeRequest) {
        results = null;
      }
    } finally {
      if (requestId === activeRequest) {
        loading = false;
      }
    }
  }

  function navigateTo(href: string) {
    const trimmed = query.trim();
    if (trimmed) recent.add(trimmed);
    closePalette();
    void goto(buildHrefWithFrom(href, currentPath));
  }

  function submitSearch() {
    const trimmed = query.trim();
    if (!trimmed) return;
    recent.add(trimmed);
    closePalette();
    void goto(`/search?q=${encodeURIComponent(trimmed)}`);
  }

  $effect(() => {
    if (!open) {
      query = "";
      results = null;
      loading = false;
      activeRequest += 1;
      return;
    }

    if (browser) {
      requestAnimationFrame(() => inputRef?.focus());
    }
  });

  $effect(() => {
    if (!browser || !open) return;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "";
    };
  });

  $effect(() => {
    if (!open) return;

    const trimmed = query.trim();
    if (trimmed.length < 2) {
      results = null;
      loading = false;
      activeRequest += 1;
      return;
    }

    loading = true;
    const timer = window.setTimeout(() => {
      void runSearch(trimmed);
    }, 250);

    return () => {
      window.clearTimeout(timer);
    };
  });
</script>

{#if open}
  <div class="fixed inset-0 z-[70] flex items-start justify-center pt-[12vh] sm:pt-[10vh]">
    <button
      type="button"
      class="absolute inset-0 bg-black/60 backdrop-blur-sm"
      aria-label="Close search"
      onclick={closePalette}
      transition:fade={{ duration: dur.normal, easing: ease.enter }}
    ></button>

    <div
      role="dialog"
      aria-modal="true"
      aria-label="Search"
      class={cn(
        "relative mx-4 flex max-h-[70vh] w-full max-w-2xl flex-col",
        "surface-elevated border border-border-subtle shadow-2xl",
      )}
      transition:flyDown
    >
      <div class="flex items-center gap-3 border-b border-border-subtle px-4 py-3">
        <Search class="h-4 w-4 shrink-0 text-text-muted" />
        <input
          bind:this={inputRef}
          bind:value={query}
          type="text"
          placeholder={`Search ${entityTerms.videos.toLowerCase()}, ${entityTerms.performers.toLowerCase()}, ${entityTerms.studios.toLowerCase()}, ${entityTerms.tags.toLowerCase()}...`}
          class="flex-1 bg-transparent text-sm text-text-primary placeholder:text-text-disabled focus:outline-none"
          onkeydown={(e) => {
            if (e.key === "Enter") {
              e.preventDefault();
              submitSearch();
            }
          }}
        />
        {#if query}
          <button
            type="button"
            class="text-text-disabled transition-colors duration-fast hover:text-text-muted"
            aria-label="Clear search"
            onclick={clearQuery}
          >
            <X class="h-3.5 w-3.5" />
          </button>
        {/if}
        <kbd class="kbd hidden shrink-0 text-text-disabled sm:inline-flex">ESC</kbd>
      </div>

      <div class="flex-1 overflow-y-auto">
        {#if !hasQuery}
          {#if recent.value.length === 0}
            <div class="px-4 py-8 text-center">
              <Search class="mx-auto mb-2 h-5 w-5 text-text-disabled opacity-50" />
              <div class="text-sm text-text-disabled">Start typing to search...</div>
            </div>
          {:else}
            <div class="py-1">
              <div class="flex items-center justify-between px-4 py-1.5">
                <span class="text-kicker">Recent Searches</span>
                <button
                  type="button"
                  class="flex items-center gap-1 text-[0.6rem] text-text-disabled transition-colors duration-fast hover:text-text-muted"
                  onclick={recent.clear}
                >
                  <Trash2 class="h-2.5 w-2.5" />
                  Clear
                </button>
              </div>
              {#each recent.value as previousQuery (previousQuery)}
                <div class="group flex items-center gap-2 px-4 py-1.5 transition-colors duration-fast hover:bg-surface-2">
                  <Clock class="h-3.5 w-3.5 shrink-0 text-text-disabled" />
                  <button
                    type="button"
                    class="flex-1 truncate text-left text-sm text-text-muted group-hover:text-text-primary"
                    onclick={() => {
                      query = previousQuery;
                    }}
                  >
                    {previousQuery}
                  </button>
                  <button
                    type="button"
                    class="opacity-0 transition-all duration-fast group-hover:opacity-100 text-text-disabled hover:text-text-muted"
                    onclick={() => recent.remove(previousQuery)}
                    aria-label={`Remove ${previousQuery}`}
                  >
                    <X class="h-3 w-3" />
                  </button>
                </div>
              {/each}
            </div>
          {/if}
        {:else if loading && !results}
          <div class="px-4 py-8 text-center">
            <div class="text-sm text-text-disabled">Searching...</div>
          </div>
        {:else if results && !hasResults && !loading}
          <div class="px-4 py-8 text-center">
            <div class="text-sm text-text-disabled">No results for "{query}"</div>
          </div>
        {:else if results && hasResults}
          <div class="py-1">
            {#each results.groups.filter((group) => group.items.length > 0) as group (group.kind)}
              <div class="py-1">
                <div class="flex items-center justify-between px-4 py-1.5">
                  <span class="text-kicker">{group.label}</span>
                  <span class="text-[0.6rem] text-text-disabled">{group.total}</span>
                </div>
                {#each group.items as item, itemIndex (item.id)}
                  <SearchResultCard
                    {item}
                    index={itemIndex}
                    variant="compact"
                    {currentPath}
                    onSelect={navigateTo}
                  />
                {/each}
              </div>
            {/each}
          </div>
        {/if}
      </div>

      {#if hasQuery}
        <div class="flex items-center justify-between border-t border-border-subtle px-4 py-2">
          <button
            type="button"
            class="flex items-center gap-1.5 text-[0.72rem] text-text-muted transition-colors duration-fast hover:text-text-accent"
            onclick={submitSearch}
          >
            <span>See all results</span>
            <ArrowRight class="h-3 w-3" />
          </button>
          <span class="font-mono text-[0.6rem] text-text-disabled">
            {loading ? "..." : `${results?.durationMs ?? 0}ms`}
          </span>
        </div>
      {/if}
    </div>
  </div>
{/if}

// apps/web/src/components/search/command-palette.tsx
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";
import {
  Search,
  X,
  Clock,
  ArrowRight,
  Trash2,
} from "lucide-react";
import { cn } from "@obscura/ui/lib/utils";
import type { SearchResultItem, SearchResultGroup } from "@obscura/contracts";
import { useSearchPalette } from "./search-context";
import { entityTerms } from "../../lib/terminology";
import { useSearch } from "../../hooks/use-search";
import { useRecentSearches } from "../../hooks/use-recent-searches";
import { SEARCH_KIND_CONFIG } from "./search-kind-config";
import { SearchResultCard } from "./search-result-card";
import { useNsfw } from "../nsfw/nsfw-context";
import { useCurrentPath } from "../../hooks/use-current-path";
import { buildHrefWithFrom } from "../../lib/back-navigation";

export function CommandPalette() {
  const { open, closePalette } = useSearchPalette();
  const { mode: nsfwMode } = useNsfw();
  const currentPath = useCurrentPath();
  const [query, setQuery] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();
  const recentSearches = useRecentSearches();
  const { data, loading } = useSearch(query, { debounceMs: 250, nsfw: nsfwMode });
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Focus input when opened, clear when closed
  useEffect(() => {
    if (open) {
      requestAnimationFrame(() => inputRef.current?.focus());
    } else {
      setQuery("");
    }
  }, [open]);

  // Lock body scroll when open
  useEffect(() => {
    if (open) {
      document.body.style.overflow = "hidden";
      return () => { document.body.style.overflow = ""; };
    }
  }, [open]);

  const handleNavigate = useCallback(
    (href: string) => {
      if (query.trim()) recentSearches.add(query.trim());
      closePalette();
      router.push(buildHrefWithFrom(href, currentPath));
    },
    [query, recentSearches, closePalette, router, currentPath]
  );

  const handleSubmit = useCallback(() => {
    if (query.trim()) {
      recentSearches.add(query.trim());
      closePalette();
      router.push(`/search?q=${encodeURIComponent(query.trim())}`);
    }
  }, [query, recentSearches, closePalette, router]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "Enter") {
        e.preventDefault();
        handleSubmit();
      }
    },
    [handleSubmit]
  );

  if (!mounted || !open) return null;

  const hasQuery = query.trim().length >= 2;
  const hasResults = data && data.groups.some((g) => g.items.length > 0);

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[12vh] sm:pt-[10vh]">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={closePalette}
      />

      {/* Panel */}
      <div
        className={cn(
          "relative w-full max-w-2xl mx-4",
          "surface-elevated shadow-2xl",
          "border border-border-subtle",
          "flex flex-col max-h-[70vh]"
        )}
      >
        {/* Search input */}
        <div className="flex items-center gap-3 px-4 py-3 border-b border-border-subtle">
          <Search className="h-4 w-4 text-text-muted shrink-0" />
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={`Search ${entityTerms.scenes.toLowerCase()}, ${entityTerms.performers.toLowerCase()}, ${entityTerms.studios.toLowerCase()}, ${entityTerms.tags.toLowerCase()}...`}
            className={cn(
              "flex-1 bg-transparent text-sm text-text-primary",
              "placeholder:text-text-disabled",
              "focus:outline-none"
            )}
          />
          {query && (
            <button
              onClick={() => setQuery("")}
              className="text-text-disabled hover:text-text-muted transition-colors duration-fast"
            >
              <X className="h-3.5 w-3.5" />
            </button>
          )}
          <kbd className="kbd hidden shrink-0 text-text-disabled sm:inline-flex">ESC</kbd>
        </div>

        {/* Results body */}
        <div className="overflow-y-auto flex-1">
          {!hasQuery && (
            <RecentSearchesList
              searches={recentSearches.searches}
              onSelect={(q) => { setQuery(q); }}
              onRemove={recentSearches.remove}
              onClear={recentSearches.clear}
            />
          )}

          {hasQuery && loading && !data && (
            <div className="px-4 py-8 text-center">
              <div className="text-text-disabled text-sm">Searching...</div>
            </div>
          )}

          {hasQuery && data && !hasResults && !loading && (
            <div className="px-4 py-8 text-center">
              <div className="text-text-disabled text-sm">No results for &ldquo;{query}&rdquo;</div>
            </div>
          )}

          {hasQuery && data && hasResults && (
            <div className="py-1">
              {data.groups
                .filter((g) => g.items.length > 0)
                .map((group) => (
                  <ResultGroup
                    key={group.kind}
                    group={group}
                    onNavigate={handleNavigate}
                    query={query}
                  />
                ))}
            </div>
          )}
        </div>

        {/* Footer */}
        {hasQuery && (
          <div className="border-t border-border-subtle px-4 py-2 flex items-center justify-between">
            <button
              onClick={handleSubmit}
              className="flex items-center gap-1.5 text-[0.72rem] text-text-muted hover:text-text-accent transition-colors duration-fast"
            >
              <span>See all results</span>
              <ArrowRight className="h-3 w-3" />
            </button>
            <span className="text-[0.6rem] text-text-disabled font-mono">
              {loading ? "..." : `${data?.durationMs ?? 0}ms`}
            </span>
          </div>
        )}
      </div>
    </div>,
    document.body
  );
}

function RecentSearchesList({
  searches,
  onSelect,
  onRemove,
  onClear,
}: {
  searches: string[];
  onSelect: (query: string) => void;
  onRemove: (query: string) => void;
  onClear: () => void;
}) {
  if (searches.length === 0) {
    return (
      <div className="px-4 py-8 text-center">
        <Search className="h-5 w-5 text-text-disabled mx-auto mb-2 opacity-50" />
        <div className="text-text-disabled text-sm">Start typing to search...</div>
      </div>
    );
  }

  return (
    <div className="py-1">
      <div className="flex items-center justify-between px-4 py-1.5">
        <span className="text-kicker">Recent Searches</span>
        <button
          onClick={onClear}
          className="flex items-center gap-1 text-[0.6rem] text-text-disabled hover:text-text-muted transition-colors duration-fast"
        >
          <Trash2 className="h-2.5 w-2.5" />
          Clear
        </button>
      </div>
      {searches.map((q) => (
        <div
          key={q}
          className="flex items-center gap-2 px-4 py-1.5 hover:bg-surface-2 transition-colors duration-fast cursor-pointer group"
        >
          <Clock className="h-3.5 w-3.5 text-text-disabled shrink-0" />
          <button
            onClick={() => onSelect(q)}
            className="flex-1 text-left text-sm text-text-muted group-hover:text-text-primary truncate"
          >
            {q}
          </button>
          <button
            onClick={(e) => { e.stopPropagation(); onRemove(q); }}
            className="opacity-0 group-hover:opacity-100 text-text-disabled hover:text-text-muted transition-all duration-fast"
          >
            <X className="h-3 w-3" />
          </button>
        </div>
      ))}
    </div>
  );
}

function ResultGroup({
  group,
  onNavigate,
  query,
}: {
  group: SearchResultGroup;
  onNavigate: (href: string) => void;
  query: string;
}) {
  const { icon: Icon, label } = SEARCH_KIND_CONFIG[group.kind];

  return (
    <div>
      <div className="flex items-center gap-2 px-4 py-1.5">
        <Icon className="h-3 w-3 text-text-disabled" />
        <span className="text-kicker">{label}</span>
        <span className="text-[0.55rem] font-mono text-text-disabled">{group.total}</span>
      </div>
      {group.items.map((item) => (
        <ResultRow key={item.id} item={item} onNavigate={onNavigate} />
      ))}
      {group.hasMore && (
        <button
          onClick={() =>
            onNavigate(`/search?q=${encodeURIComponent(query)}&kinds=${group.kind}`)
          }
          className="flex items-center gap-1.5 px-4 py-1 text-[0.68rem] text-text-muted hover:text-text-accent transition-colors duration-fast w-full"
        >
          <ArrowRight className="h-2.5 w-2.5" />
        <span>View all {group.total} {label.toLowerCase()}</span>
        </button>
      )}
    </div>
  );
}

function ResultRow({
  item,
  onNavigate,
}: {
  item: SearchResultItem;
  onNavigate: (href: string) => void;
}) {
  return <SearchResultCard item={item} variant="compact" onSelect={onNavigate} />;
}
