// apps/web-svelte/src/routes/tags/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { Tag as TagIcon, Star } from "@lucide/svelte";
  import { Badge } from "@obscura/ui-svelte";
  import FilterBar, { type SortDir } from "$lib/components/FilterBar.svelte";
  import { toApiUrl } from "$lib/api/core";

  let { data } = $props();

  const sortOptions = [
    { value: "videos", label: "Usage Count" },
    { value: "name", label: "Name A-Z" },
  ];

  const sortBy = $derived(page.url.searchParams.get("sort") ?? "videos");
  const sortDir: SortDir = $derived(
    page.url.searchParams.get("order") === "asc" ? "asc" : "desc",
  );
  const searchQuery = $derived(page.url.searchParams.get("search") ?? "");

  function updateUrl(patch: Record<string, string | null | undefined>) {
    const params = new URLSearchParams(page.url.searchParams);
    for (const [k, v] of Object.entries(patch)) {
      if (v === null || v === undefined || v === "") params.delete(k);
      else params.set(k, v);
    }
    const qs = params.toString();
    void goto(qs ? `/tags?${qs}` : "/tags", { keepFocus: true, noScroll: true });
  }

  function onClearFiltersAndSort() {
    void goto("/tags", { keepFocus: true, noScroll: true });
  }

  const canClearFiltersAndSort = $derived(
    !!searchQuery || sortBy !== "videos" || sortDir !== "desc",
  );

  const filtered = $derived.by(() => {
    const q = searchQuery.trim().toLowerCase();
    let list = data.tags;
    if (q) list = list.filter((t) => t.name.toLowerCase().includes(q));
    const sign = sortDir === "asc" ? 1 : -1;
    list = [...list].sort((a, b) => {
      switch (sortBy) {
        case "videos":
          // "Usage Count" is videos + images per the React label.
          return (
            sign *
            (((a.videoCount ?? 0) + (a.imageCount ?? 0)) -
              ((b.videoCount ?? 0) + (b.imageCount ?? 0)))
          );
        case "name":
        default:
          return sign * a.name.localeCompare(b.name);
      }
    });
    return list;
  });
</script>

<svelte:head>
  <title>Obscura</title>
</svelte:head>

<div class="space-y-6">
  <div class="flex items-start justify-between gap-4">
    <div>
      <h1 class="flex items-center gap-2.5">
        <TagIcon class="h-5 w-5 text-text-accent" />
        Tags
      </h1>
      <p class="text-text-muted text-[0.78rem] mt-1">Browse tags in your library</p>
    </div>
    <span class="text-mono-sm text-text-disabled mt-1">{filtered.length} total</span>
  </div>

  <FilterBar
    {sortOptions}
    {sortBy}
    {sortDir}
    onSortChange={(sort: string, dir?: SortDir) => updateUrl({ sort, order: dir ?? sortDir })}
    {searchQuery}
    onSearchChange={(q) => updateUrl({ search: q || null })}
    showViewToggle={false}
    {onClearFiltersAndSort}
    {canClearFiltersAndSort}
  />

  {#if filtered.length === 0}
    <div class="surface-panel p-8 text-center">
      <TagIcon class="h-10 w-10 mx-auto mb-3 text-text-disabled" />
      <p class="text-body text-text-muted">
        {searchQuery ? "No tags match that search." : "No tags yet."}
      </p>
      {#if !searchQuery}
        <p class="text-body-sm text-text-disabled mt-1">
          Tags you create from the Identify or Edit flows will appear here.
        </p>
      {/if}
    </div>
  {:else}
    <div class="grid grid-cols-2 gap-2.5 sm:grid-cols-3">
      {#each filtered as tag (tag.id)}
        <a
          href={`/tags/${encodeURIComponent(tag.name)}`}
          class="surface-card-sharp p-3 flex flex-col gap-2 hover:border-border-accent transition-colors duration-fast"
        >
          <div class="flex items-center gap-2">
            {#if tag.imagePath}
              <img
                src={toApiUrl(tag.imagePath)}
                alt=""
                loading="lazy"
                decoding="async"
                class="h-6 w-6 object-cover shrink-0 border border-border-subtle"
              />
            {:else}
              <TagIcon class="h-4 w-4 text-accent-500 shrink-0" />
            {/if}
            <span class="truncate text-body font-medium text-text-primary">{tag.name}</span>
            {#if tag.favorite}
              <Star class="h-3 w-3 text-accent-500 fill-current ml-auto shrink-0" />
            {/if}
          </div>
          <div class="flex flex-wrap items-center gap-1.5">
            {#if tag.videoCount > 0}
              <Badge>
                {#snippet children()}
                  {tag.videoCount} video{tag.videoCount === 1 ? "" : "s"}
                {/snippet}
              </Badge>
            {/if}
            {#if tag.imageCount > 0}
              <Badge>
                {#snippet children()}
                  {tag.imageCount} image{tag.imageCount === 1 ? "" : "s"}
                {/snippet}
              </Badge>
            {/if}
            {#if tag.isNsfw}
              <Badge variant="warning">
                {#snippet children()}NSFW{/snippet}
              </Badge>
            {/if}
          </div>
        </a>
      {/each}
    </div>
  {/if}
</div>

// apps/web/src/app/(app)/tags/page.tsx
"use client";

import { useEffect, useState, useMemo } from "react";
import { Tag, Search, Loader2 } from "lucide-react";
import Link from "next/link";
import { cn } from "@obscura/ui";
import { fetchTags, type TagItem } from "../../../lib/api";

export default function TagsPage() {
  const [tags, setTags] = useState<TagItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  useEffect(() => {
    fetchTags()
      .then((r) => setTags(r.tags))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const sorted = useMemo(
    () => [...tags].sort((a, b) => b.sceneCount - a.sceneCount),
    [tags]
  );

  const filtered = useMemo(() => {
    if (!search.trim()) return sorted;
    const term = search.toLowerCase();
    return sorted.filter((t) => t.name.toLowerCase().includes(term));
  }, [sorted, search]);

  const maxCount = sorted[0]?.sceneCount ?? 1;
  const totalScenes = tags.reduce((sum, t) => sum + t.sceneCount, 0);

  return (
    <div className="space-y-4">
      {/* Page header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="flex items-center gap-2.5">
            <Tag className="h-5 w-5 text-text-accent" />
            Tags
          </h1>
          <p className="text-text-muted text-[0.78rem] mt-1">
            Browse and filter by tag
          </p>
        </div>
        <span className="text-mono-sm text-text-disabled mt-1">
          {loading ? "…" : `${tags.length} tags`}
        </span>
      </div>

      {/* Stats strip */}
      {!loading && tags.length > 0 && (
        <div className="grid grid-cols-2 gap-2">
          <div className="surface-stat px-3 py-2.5">
            <div className="flex items-center gap-1.5 mb-1 text-text-disabled">
              <Tag className="h-3.5 w-3.5" />
              <span className="text-kicker" style={{ color: "inherit" }}>Total Tags</span>
            </div>
            <div className="text-lg font-semibold text-text-primary leading-tight">
              {tags.length}
            </div>
          </div>
          <div className="surface-stat px-3 py-2.5">
            <div className="flex items-center gap-1.5 mb-1 text-text-disabled">
              <Tag className="h-3.5 w-3.5" />
              <span className="text-kicker" style={{ color: "inherit" }}>Tagged Scenes</span>
            </div>
            <div className="text-lg font-semibold text-text-primary leading-tight">
              {totalScenes}
            </div>
          </div>
        </div>
      )}

      {/* Search toolbar */}
      {!loading && tags.length > 0 && (
        <div className="surface-well flex items-center gap-2 p-2">
          <div className="flex-1 relative">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-text-disabled pointer-events-none" />
            <input
              type="text"
              placeholder="Search tags…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="control-input w-full pl-8 pr-3 py-1.5 text-sm"
            />
          </div>
          {search && (
            <span className="text-mono-sm text-text-disabled">
              {filtered.length} result{filtered.length !== 1 ? "s" : ""}
            </span>
          )}
        </div>
      )}

      {loading ? (
        <div className="surface-well p-12 flex items-center justify-center">
          <Loader2 className="h-6 w-6 text-text-disabled animate-spin" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="surface-well p-12 text-center">
          <Tag className="h-10 w-10 text-text-disabled mx-auto mb-3" />
          <p className="text-text-muted text-sm">
            {search ? "No tags match your search." : "No tags in the library yet."}
          </p>
          {search && (
            <button
              onClick={() => setSearch("")}
              className="text-text-accent text-xs mt-2 hover:text-text-accent-bright transition-colors duration-fast"
            >
              Clear search
            </button>
          )}
        </div>
      ) : (
        <>
          {/* Tag cloud */}
          {!search && (
            <div className="surface-panel p-6">
              <h4 className="text-kicker mb-4">Tag Cloud</h4>
              <div className="flex flex-wrap gap-2 justify-center">
                {sorted.slice(0, 40).map((tag) => {
                  const intensity = tag.sceneCount / maxCount;
                  return (
                    <Link
                      key={tag.id}
                      href={`/tags/${encodeURIComponent(tag.name)}`}
                      className={cn(
                        "rounded-md border px-3 py-1.5 transition-all duration-fast",
                        "hover:border-border-accent hover:bg-accent-950 hover:text-text-accent",
                        intensity > 0.6
                          ? "border-border-accent text-accent-400 text-base font-medium"
                          : intensity > 0.3
                            ? "border-border-default text-text-secondary text-sm"
                            : "border-border-subtle text-text-muted text-xs"
                      )}
                    >
                      {tag.name}
                      <span className="ml-1.5 text-text-disabled text-xs">
                        {tag.sceneCount}
                      </span>
                    </Link>
                  );
                })}
              </div>
            </div>
          )}

          {/* Tag list */}
          <section>
            <h4 className="text-kicker mb-3">
              {search ? `Results (${filtered.length})` : "All Tags"}
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
              {filtered.map((tag) => (
                <Link
                  key={tag.id}
                  href={`/tags/${encodeURIComponent(tag.name)}`}
                  className="surface-card flex items-center justify-between p-3 group"
                >
                  <span className="text-sm group-hover:text-text-accent transition-colors duration-fast truncate">
                    {tag.name}
                  </span>
                  <span className="text-mono-sm text-text-disabled flex-shrink-0 ml-2">
                    {tag.sceneCount}
                  </span>
                </Link>
              ))}
            </div>
          </section>
        </>
      )}
    </div>
  );
}
