// apps/web-svelte/src/lib/components/AddToCollectionModal.svelte
<script lang="ts">
  import { invalidate } from "$app/navigation";
  import {
    Check,
    FolderOpen,
    Hand,
    Loader2,
    Plus,
    Shuffle,
    X,
    Zap,
  } from "@lucide/svelte";
  import type {
    CollectionEntityType,
    CollectionListItemDto,
  } from "@obscura/contracts";
  import { Button } from "@obscura/ui-svelte";
  import {
    addCollectionItems,
    createCollection,
    fetchCollections,
  } from "$lib/api/media";

  interface Props {
    open: boolean;
    onClose: () => void;
    entityType: CollectionEntityType;
    entityId: string;
    entityTitle?: string;
    items?: { entityType: CollectionEntityType; entityId: string }[];
  }

  let {
    open,
    onClose,
    entityType,
    entityId,
    entityTitle,
    items: expandedItems,
  }: Props = $props();

  const modeIcons = {
    manual: Hand,
    dynamic: Zap,
    hybrid: Shuffle,
  } as const;

  let collections = $state<CollectionListItemDto[]>([]);
  let isLoading = $state(false);
  let selectedIds = $state<string[]>([]);
  let addingToIds = $state<string[]>([]);
  let addedIds = $state<string[]>([]);
  let isCreating = $state(false);

  const itemsToAdd = $derived(
    expandedItems ?? [{ entityType, entityId }],
  );

  $effect(() => {
    if (!open) return;

    let cancelled = false;
    selectedIds = [];
    addingToIds = [];
    addedIds = [];
    isLoading = true;

    void fetchCollections({ limit: 200, sort: "updated", order: "desc" })
      .then((response) => {
        if (cancelled) return;
        collections = response.items;
      })
      .catch(() => {
        if (cancelled) return;
        collections = [];
      })
      .finally(() => {
        if (!cancelled) isLoading = false;
      });

    return () => {
      cancelled = true;
    };
  });

  function toggleSelection(collectionId: string) {
    selectedIds = selectedIds.includes(collectionId)
      ? selectedIds.filter((id) => id !== collectionId)
      : [...selectedIds, collectionId];
  }

  async function refreshCollectionDependencies(collectionIds: Iterable<string>) {
    await invalidate("collections");
    await Promise.all(
      Array.from(collectionIds, (collectionId) =>
        invalidate(`collections:${collectionId}`),
      ),
    );
  }

  async function handleAdd() {
    if (selectedIds.length === 0) return;

    const ids = [...selectedIds];
    addingToIds = ids;

    await Promise.allSettled(
      ids.map(async (collectionId) => {
        try {
          await addCollectionItems(collectionId, { items: itemsToAdd });
          addedIds = [...addedIds, collectionId];
        } catch {
          // Ignore per-collection failures so the user still gets partial success.
        }
      }),
    );

    await refreshCollectionDependencies(ids);
    addingToIds = [];
    window.setTimeout(() => onClose(), 400);
  }

  async function handleCreateAndAdd() {
    isCreating = true;
    try {
      const collection = await createCollection({
        name: entityTitle ? `${entityTitle} collection` : "New Collection",
      });

      await addCollectionItems(collection.id, { items: itemsToAdd });

      const typeCounts = { video: 0, gallery: 0, image: 0, "audio-track": 0 };
      for (const item of itemsToAdd) {
        typeCounts[item.entityType] += 1;
      }

      collections = [
        {
          ...collection,
          itemCount: itemsToAdd.length,
          typeCounts,
        } as CollectionListItemDto,
        ...collections,
      ];
      addedIds = [...addedIds, collection.id];
      await refreshCollectionDependencies([collection.id]);
    } finally {
      isCreating = false;
    }
  }
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <button
      type="button"
      class="absolute inset-0 bg-black/60 backdrop-blur-sm"
      onclick={onClose}
      aria-label="Close add to collection modal"
    ></button>

    <div class="relative z-10 w-full max-w-md surface-elevated">
      <div class="flex items-center justify-between border-b border-border-subtle px-4 py-3">
        <h2 class="text-sm font-heading font-medium text-text-primary">
          Add to Collection
        </h2>
        <button
          type="button"
          onclick={onClose}
          class="p-1 text-text-muted transition-colors hover:text-text-secondary"
          aria-label="Close add to collection modal"
        >
          <X class="h-4 w-4" />
        </button>
      </div>

      <div class="max-h-[60vh] overflow-y-auto p-2">
        <button
          type="button"
          onclick={() => void handleCreateAndAdd()}
          disabled={isCreating}
          class="mb-1 flex w-full items-center gap-2 border-b border-border-subtle px-3 py-2.5 text-left transition-colors hover:bg-surface-2"
        >
          {#if isCreating}
            <Loader2 class="h-4 w-4 animate-spin text-text-accent" />
          {:else}
            <Plus class="h-4 w-4 text-text-accent" />
          {/if}
          <span class="text-[0.78rem] font-medium text-text-accent">
            {isCreating ? "Creating..." : "Create new collection"}
          </span>
        </button>

        {#if isLoading}
          <div class="flex items-center justify-center py-8">
            <Loader2 class="h-5 w-5 animate-spin text-text-muted" />
          </div>
        {:else if collections.length === 0}
          <div class="py-8 text-center text-sm text-text-muted">
            No collections yet
          </div>
        {:else}
          <div class="space-y-[1px]">
            {#each collections as collection (collection.id)}
              {@const isSelected = selectedIds.includes(collection.id)}
              {@const isAdding = addingToIds.includes(collection.id)}
              {@const isAdded = addedIds.includes(collection.id)}
              {@const ModeIcon = modeIcons[collection.mode]}

              <button
                type="button"
                onclick={() => {
                  if (isAdded) return;
                  toggleSelection(collection.id);
                }}
                disabled={isAdding || isAdded}
                class={[
                  "flex w-full items-center gap-2 px-3 py-2 text-left transition-colors disabled:cursor-default",
                  isSelected
                    ? "bg-accent-brass/10"
                    : isAdded
                      ? "bg-green-500/5"
                      : "hover:bg-surface-2",
                ]}
              >
                <div
                  class={[
                    "flex h-4 w-4 shrink-0 items-center justify-center border",
                    isSelected || isAdded
                      ? "border-accent-brass/50 bg-accent-brass/20"
                      : "border-border-default",
                  ]}
                >
                  {#if isAdding}
                    <Loader2 class="h-3 w-3 animate-spin text-text-accent" />
                  {:else if isAdded}
                    <Check class="h-3 w-3 text-green-400" />
                  {:else if isSelected}
                    <Check class="h-3 w-3 text-text-accent" />
                  {/if}
                </div>

                <FolderOpen class="h-3.5 w-3.5 shrink-0 text-text-muted" />
                <div class="min-w-0 flex-1">
                  <span class="block truncate text-[0.78rem] text-text-primary">
                    {collection.name}
                  </span>
                </div>
                {#if isAdded}
                  <span class="shrink-0 text-[0.6rem] font-mono text-green-400">
                    Added
                  </span>
                {/if}
                <span
                  class="inline-flex shrink-0 items-center gap-0.5 text-[0.65rem] font-mono text-text-disabled"
                >
                  <ModeIcon class="h-2.5 w-2.5" />
                  {collection.itemCount}
                </span>
              </button>
            {/each}
          </div>
        {/if}
      </div>

      {#if selectedIds.length > 0}
        <div class="flex items-center justify-between border-t border-border-subtle px-4 py-3">
          <span class="text-[0.75rem] text-text-muted">
            {selectedIds.length} selected
          </span>
          <Button size="sm" onclick={() => void handleAdd()} disabled={addingToIds.length > 0}>
            {#if addingToIds.length > 0}
              <Loader2 class="h-3.5 w-3.5 animate-spin" />
            {:else}
              <Check class="h-3.5 w-3.5" />
            {/if}
            Confirm
          </Button>
        </div>
      {/if}
    </div>
  </div>
{/if}

// apps/web/src/components/collections/add-to-collection-modal.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import {
  X,
  FolderOpen,
  Plus,
  Check,
  Loader2,
  Hand,
  Zap,
  Shuffle,
} from "lucide-react";
import { Button } from "@obscura/ui/primitives/button";
import type {
  CollectionListItemDto,
  CollectionEntityType,
} from "@obscura/contracts";
import {
  fetchCollections,
  addCollectionItems,
  createCollection,
} from "../../lib/api/media";

const modeIcons = {
  manual: Hand,
  dynamic: Zap,
  hybrid: Shuffle,
};

interface AddToCollectionModalProps {
  open: boolean;
  onClose: () => void;
  entityType: CollectionEntityType;
  entityId: string;
  entityTitle?: string;
}

export function AddToCollectionModal({
  open,
  onClose,
  entityType,
  entityId,
  entityTitle,
}: AddToCollectionModalProps) {
  const [collections, setCollections] = useState<CollectionListItemDto[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [addingToIds, setAddingToIds] = useState<Set<string>>(new Set());
  const [addedIds, setAddedIds] = useState<Set<string>>(new Set());
  const [isCreating, setIsCreating] = useState(false);

  useEffect(() => {
    if (!open) return;
    setIsLoading(true);
    setSelectedIds(new Set());
    setAddedIds(new Set());
    fetchCollections({ limit: 200, sort: "updated", order: "desc" })
      .then((res) => setCollections(res.items))
      .catch(() => setCollections([]))
      .finally(() => setIsLoading(false));
  }, [open]);

  const handleAdd = useCallback(async () => {
    if (selectedIds.size === 0) return;
    setAddingToIds(new Set(selectedIds));

    for (const collId of selectedIds) {
      try {
        await addCollectionItems(collId, {
          items: [{ entityType, entityId }],
        });
        setAddedIds((prev) => new Set([...prev, collId]));
      } catch (err) {
        console.error(`Failed to add to ${collId}:`, err);
      }
    }

    setAddingToIds(new Set());
    setTimeout(onClose, 600);
  }, [selectedIds, entityType, entityId, onClose]);

  const handleCreateAndAdd = useCallback(async () => {
    setIsCreating(true);
    try {
      const coll = await createCollection({
        name: entityTitle
          ? `${entityTitle} collection`
          : "New Collection",
      });

      // Add the item to the new collection
      await addCollectionItems(coll.id, {
        items: [{ entityType, entityId }],
      });

      // Immediately insert the new collection into the list so the user
      // sees it appear with a success checkmark — no delay.
      setCollections((prev) => [
        {
          ...coll,
          itemCount: 1,
          typeCounts: {
            scene: entityType === "scene" ? 1 : 0,
            gallery: entityType === "gallery" ? 1 : 0,
            image: entityType === "image" ? 1 : 0,
            "audio-track": entityType === "audio-track" ? 1 : 0,
          },
        } as CollectionListItemDto,
        ...prev,
      ]);
      setAddedIds((prev) => new Set([...prev, coll.id]));
    } catch (err) {
      console.error("Failed to create collection:", err);
    } finally {
      setIsCreating(false);
    }
  }, [entityType, entityId, entityTitle]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative z-10 w-full max-w-md bg-surface-1 border border-border-default shadow-xl">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border-subtle">
          <h2 className="text-sm font-heading font-medium text-text-primary">
            Add to Collection
          </h2>
          <button
            onClick={onClose}
            className="p-1 text-text-muted hover:text-text-secondary transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Content */}
        <div className="max-h-[60vh] overflow-y-auto p-2">
          {/* Create new */}
          <button
            onClick={handleCreateAndAdd}
            disabled={isCreating}
            className="w-full flex items-center gap-2 px-3 py-2.5 text-left hover:bg-surface-2 transition-colors border-b border-border-subtle mb-1"
          >
            {isCreating ? (
              <Loader2 className="h-4 w-4 text-text-accent animate-spin" />
            ) : (
              <Plus className="h-4 w-4 text-text-accent" />
            )}
            <span className="text-[0.78rem] text-text-accent font-medium">
              {isCreating ? "Creating..." : "Create new collection"}
            </span>
          </button>

          {isLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-5 w-5 text-text-muted animate-spin" />
            </div>
          ) : collections.length === 0 ? (
            <div className="py-8 text-center text-text-muted text-sm">
              No collections yet
            </div>
          ) : (
            <div className="space-y-[1px]">
              {collections.map((coll) => {
                const isSelected = selectedIds.has(coll.id);
                const isAdding = addingToIds.has(coll.id);
                const isAdded = addedIds.has(coll.id);
                const ModeIcon = modeIcons[coll.mode];

                return (
                  <button
                    key={coll.id}
                    onClick={() => {
                      if (isAdded) return;
                      setSelectedIds((prev) => {
                        const next = new Set(prev);
                        if (next.has(coll.id)) {
                          next.delete(coll.id);
                        } else {
                          next.add(coll.id);
                        }
                        return next;
                      });
                    }}
                    disabled={isAdding || isAdded}
                    className={`w-full flex items-center gap-2 px-3 py-2 text-left transition-colors ${
                      isSelected
                        ? "bg-accent-brass/10"
                        : isAdded
                          ? "bg-green-500/5"
                          : "hover:bg-surface-2"
                    } disabled:cursor-default`}
                  >
                    {/* Checkbox area */}
                    <div
                      className={`h-4 w-4 flex items-center justify-center border flex-shrink-0 ${
                        isSelected || isAdded
                          ? "border-accent-brass/50 bg-accent-brass/20"
                          : "border-border-default"
                      }`}
                    >
                      {isAdding && (
                        <Loader2 className="h-3 w-3 text-text-accent animate-spin" />
                      )}
                      {isAdded && (
                        <Check className="h-3 w-3 text-green-400" />
                      )}
                      {isSelected && !isAdding && !isAdded && (
                        <Check className="h-3 w-3 text-text-accent" />
                      )}
                    </div>

                    {/* Collection info */}
                    <FolderOpen className="h-3.5 w-3.5 text-text-muted flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <span className="text-[0.78rem] text-text-primary truncate block">
                        {coll.name}
                      </span>
                    </div>
                    {isAdded && (
                      <span className="text-[0.6rem] font-mono text-green-400 flex-shrink-0">
                        Added
                      </span>
                    )}
                    <span className="text-[0.65rem] font-mono text-text-disabled flex-shrink-0 inline-flex items-center gap-0.5">
                      <ModeIcon className="h-2.5 w-2.5" />
                      {coll.itemCount}
                    </span>
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer */}
        {selectedIds.size > 0 && (
          <div className="px-4 py-3 border-t border-border-subtle flex items-center justify-between">
            <span className="text-[0.75rem] text-text-muted">
              {selectedIds.size} selected
            </span>
            <Button
              onClick={handleAdd}
              disabled={addingToIds.size > 0}
              size="sm"
            >
              {addingToIds.size > 0 ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Check className="h-3.5 w-3.5" />
              )}
              Confirm
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
