// apps/web-svelte/src/lib/components/collections/ConditionBuilder.svelte
<script lang="ts">
  import { Loader2, Film, Images, Layers, Music } from "@lucide/svelte";
  import type {
    CollectionRuleGroup,
    CollectionRulePreviewDto,
    CollectionEntityType,
  } from "@obscura/contracts";
  import { COLLECTION_RULE_FIELDS } from "@obscura/contracts";
  import ConditionGroup from "./ConditionGroup.svelte";
  import CollectionItemCard from "./CollectionItemCard.svelte";
  import { previewCollectionRules } from "$lib/api/media";
  import type { SuggestionItem } from "$lib/collection-suggestions";

  interface Props {
    ruleTree: CollectionRuleGroup | null;
    onChange: (ruleTree: CollectionRuleGroup | null) => void;
    availableTags?: SuggestionItem[];
    availablePerformers?: SuggestionItem[];
    availableStudios?: SuggestionItem[];
  }

  let {
    ruleTree,
    onChange,
    availableTags = [],
    availablePerformers = [],
    availableStudios = [],
  }: Props = $props();

  function emptyRuleTree(): CollectionRuleGroup {
    const defaultField = COLLECTION_RULE_FIELDS[0];
    return {
      type: "group",
      operator: "and",
      children: [
        {
          type: "condition",
          entityTypes: [],
          field: defaultField.field,
          operator: defaultField.operators[0],
          value: null,
        },
      ],
    };
  }

  const typeLabels: Record<CollectionEntityType, string> = {
    video: "videos",
    gallery: "galleries",
    image: "images",
    "audio-track": "audio tracks",
  };
  const typeIcons: Record<CollectionEntityType, typeof Film> = {
    video: Film,
    gallery: Images,
    image: Layers,
    "audio-track": Music,
  };

  let preview = $state<CollectionRulePreviewDto | null>(null);
  let isPreviewing = $state(false);
  let debounce: ReturnType<typeof setTimeout> | null = null;

  const tree = $derived(ruleTree ?? emptyRuleTree());

  async function runPreview(currentTree: CollectionRuleGroup) {
    isPreviewing = true;
    try {
      preview = await previewCollectionRules(currentTree);
    } catch {
      // silent
    } finally {
      isPreviewing = false;
    }
  }

  $effect(() => {
    const t = ruleTree;
    if (!t || t.children.length === 0) {
      preview = null;
      return;
    }
    if (debounce) clearTimeout(debounce);
    debounce = setTimeout(() => void runPreview(t), 800);
    return () => {
      if (debounce) clearTimeout(debounce);
    };
  });
</script>

<div class="space-y-4">
  <section class="surface-well p-4">
    <div class="flex items-center justify-between mb-3">
      <h2 class="text-sm font-heading font-medium text-text-secondary">Dynamic Rules</h2>
      {#if isPreviewing}
        <span class="inline-flex items-center gap-1.5 text-[0.7rem] text-text-muted">
          <Loader2 class="h-3 w-3 animate-spin" />
          Updating preview...
        </span>
      {/if}
    </div>

    <ConditionGroup
      group={tree}
      onChange={(updated) => onChange(updated)}
      {availableTags}
      {availablePerformers}
      {availableStudios}
    />
  </section>

  {#if preview}
    <section class="surface-well p-4 space-y-3">
      <div class="flex items-center justify-between">
        <h2 class="text-sm font-heading font-medium text-text-secondary">Preview</h2>
        <span class="text-[0.78rem] font-mono text-text-accent">
          {preview.total} match{preview.total !== 1 ? "es" : ""}
        </span>
      </div>

      <div class="flex flex-wrap gap-3">
        {#each Object.entries(preview.byType).filter(([, c]) => (c as number) > 0) as [type, count] (type)}
          {@const Icon = typeIcons[type as CollectionEntityType]}
          <span class="inline-flex items-center gap-1 text-[0.75rem] text-text-muted">
            <Icon class="h-3 w-3" />
            {count} {typeLabels[type as CollectionEntityType]}
          </span>
        {/each}
      </div>

      {#if preview.sample.length > 0}
        <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2.5">
          {#each preview.sample as item (item.id)}
            <CollectionItemCard {item} />
          {/each}
        </div>
      {/if}

      {#if preview.total > preview.sample.length}
        <p class="text-[0.7rem] text-text-disabled text-center">
          Showing {preview.sample.length} of {preview.total} matches
        </p>
      {/if}
    </section>
  {/if}
</div>

// apps/web/src/components/collections/condition-builder.tsx
"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { Eye, Loader2, Film, Images, Layers, Music } from "lucide-react";
import type {
  CollectionRuleGroup,
  CollectionRulePreviewDto,
  CollectionEntityType,
} from "@obscura/contracts";
import { COLLECTION_RULE_FIELDS } from "@obscura/contracts";
import { ConditionGroup } from "./condition-group";
import { CollectionItemCard } from "./collection-item-card";
import { previewCollectionRules } from "../../lib/api/media";
import type { SuggestionItem } from "../routes/collection-editor-client";

interface ConditionBuilderProps {
  ruleTree: CollectionRuleGroup | null;
  onChange: (ruleTree: CollectionRuleGroup | null) => void;
  availableTags?: SuggestionItem[];
  availablePerformers?: SuggestionItem[];
  availableStudios?: SuggestionItem[];
}

function emptyRuleTree(): CollectionRuleGroup {
  const defaultField = COLLECTION_RULE_FIELDS[0];
  return {
    type: "group",
    operator: "and",
    children: [
      {
        type: "condition",
        entityTypes: [],
        field: defaultField.field,
        operator: defaultField.operators[0],
        value: null,
      },
    ],
  };
}

const typeLabels: Record<CollectionEntityType, string> = {
  video: "videos",
  gallery: "galleries",
  image: "images",
  "audio-track": "audio tracks",
};

const typeIcons: Record<CollectionEntityType, typeof Film> = {
  video: Film,
  gallery: Images,
  image: Layers,
  "audio-track": Music,
};

export function ConditionBuilder({
  ruleTree,
  onChange,
  availableTags = [],
  availablePerformers = [],
  availableStudios = [],
}: ConditionBuilderProps) {
  const [preview, setPreview] = useState<CollectionRulePreviewDto | null>(null);
  const [isPreviewing, setIsPreviewing] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const tree = ruleTree ?? emptyRuleTree();

  // Live preview: debounce rule changes and auto-preview
  const triggerPreview = useCallback(
    async (currentTree: CollectionRuleGroup) => {
      setIsPreviewing(true);
      try {
        const result = await previewCollectionRules(currentTree);
        setPreview(result);
      } catch {
        // Preview failed silently — user can still save
      } finally {
        setIsPreviewing(false);
      }
    },
    [],
  );

  // Auto-preview on rule tree changes (debounced 800ms)
  useEffect(() => {
    if (!ruleTree || ruleTree.children.length === 0) {
      setPreview(null);
      return;
    }

    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      triggerPreview(ruleTree);
    }, 800);

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [ruleTree, triggerPreview]);

  return (
    <div className="space-y-4">
      {/* Rule tree editor */}
      <section className="surface-well p-4">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-heading font-medium text-text-secondary">
            Dynamic Rules
          </h2>
          {isPreviewing && (
            <span className="inline-flex items-center gap-1.5 text-[0.7rem] text-text-muted">
              <Loader2 className="h-3 w-3 animate-spin" />
              Updating preview...
            </span>
          )}
        </div>

        <ConditionGroup
          group={tree}
          onChange={(updated) => onChange(updated)}
          availableTags={availableTags}
          availablePerformers={availablePerformers}
          availableStudios={availableStudios}
        />
      </section>

      {/* Live preview results */}
      {preview && (
        <section className="surface-well p-4 space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-heading font-medium text-text-secondary">
              Preview
            </h2>
            <span className="text-[0.78rem] font-mono text-text-accent">
              {preview.total} match{preview.total !== 1 ? "es" : ""}
            </span>
          </div>

          {/* Type breakdown */}
          <div className="flex flex-wrap gap-3">
            {(
              Object.entries(preview.byType) as [CollectionEntityType, number][]
            )
              .filter(([, count]) => count > 0)
              .map(([type, count]) => {
                const Icon = typeIcons[type];
                return (
                  <span
                    key={type}
                    className="inline-flex items-center gap-1 text-[0.75rem] text-text-muted"
                  >
                    <Icon className="h-3 w-3" />
                    {count} {typeLabels[type]}
                  </span>
                );
              })}
          </div>

          {/* Sample items */}
          {preview.sample.length > 0 && (
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2.5">
              {preview.sample.map((item) => (
                <CollectionItemCard key={item.id} item={item} />
              ))}
            </div>
          )}

          {preview.total > preview.sample.length && (
            <p className="text-[0.7rem] text-text-disabled text-center">
              Showing {preview.sample.length} of {preview.total} matches
            </p>
          )}
        </section>
      )}
    </div>
  );
}
