// apps/web-svelte/src/lib/components/PlaylistController.svelte
<script lang="ts">
  import { ChevronDown, ChevronUp, Film, Images, Layers, Music, Repeat, Shuffle, SkipBack, SkipForward, X } from "@lucide/svelte";
  import type { CollectionEntityType } from "@obscura/contracts";
  import { usePlaylist } from "$lib/stores/playlist.svelte";
  import { getEntityHref } from "./collections/collection-item-helpers";
  import PlaylistQueueSheet from "./PlaylistQueueSheet.svelte";

  const playlist = usePlaylist();

  const typeIcons: Record<CollectionEntityType, typeof Film> = {
    video: Film,
    gallery: Images,
    image: Layers,
    "audio-track": Music,
  };

  let showQueue = $state(false);

  const currentTitle = $derived(
    ((playlist.currentItem?.entity as Record<string, unknown> | undefined)?.title as string | undefined) ?? "Untitled",
  );
  const CurrentTypeIcon = $derived(
    playlist.currentItem ? typeIcons[playlist.currentItem.entityType] : Film,
  );
</script>

{#if playlist.isActive}
  <PlaylistQueueSheet open={showQueue} onClose={() => (showQueue = false)} />

  <div class="fixed bottom-14 left-0 right-0 z-[55] flex h-14 items-center gap-3 border-t border-border-subtle bg-surface-1/95 px-4 backdrop-blur-xl md:bottom-0">
    <div class="flex min-w-0 flex-1 items-center gap-2">
      <CurrentTypeIcon class="h-4 w-4 shrink-0 text-text-accent" />
      <div class="min-w-0">
        <a
          href={playlist.currentItem ? getEntityHref(playlist.currentItem) : "#"}
          class="block truncate text-[0.78rem] font-medium leading-tight text-text-primary transition-colors hover:text-text-accent"
        >
          {currentTitle}
        </a>
        <a
          href={playlist.collectionId ? `/collections/${playlist.collectionId}` : "/collections"}
          class="block truncate text-[0.65rem] leading-tight text-text-muted transition-colors hover:text-text-accent"
        >
          {playlist.collectionName} — {playlist.orderPosition + 1}/{playlist.items.length}
        </a>
      </div>
    </div>

    <div class="flex items-center gap-1">
      <button
        type="button"
        class={`p-1.5 transition-colors ${playlist.shuffle ? "text-text-accent" : "text-text-muted hover:text-text-secondary"}`}
        title="Shuffle"
        onclick={() => playlist.toggleShuffle()}
      >
        <Shuffle class="h-3.5 w-3.5" />
      </button>

      <button
        type="button"
        class="p-1.5 text-text-secondary transition-colors hover:text-text-primary"
        title="Previous"
        onclick={() => playlist.previous()}
      >
        <SkipBack class="h-4 w-4" />
      </button>

      <button
        type="button"
        class="p-1.5 text-text-secondary transition-colors hover:text-text-primary"
        title="Next"
        onclick={() => playlist.next()}
      >
        <SkipForward class="h-4 w-4" />
      </button>

      <button
        type="button"
        class={`p-1.5 transition-colors ${playlist.loop ? "text-text-accent" : "text-text-muted hover:text-text-secondary"}`}
        title="Loop"
        onclick={() => playlist.toggleLoop()}
      >
        <Repeat class="h-3.5 w-3.5" />
      </button>
    </div>

    <div class="flex items-center gap-1">
      <button
        type="button"
        class="p-1.5 text-text-muted transition-colors hover:text-text-secondary"
        title="Queue"
        onclick={() => (showQueue = !showQueue)}
      >
        {#if showQueue}
          <ChevronDown class="h-4 w-4" />
        {:else}
          <ChevronUp class="h-4 w-4" />
        {/if}
      </button>
      <button
        type="button"
        class="p-1.5 text-text-muted transition-colors hover:text-error-text"
        title="End playlist"
        onclick={() => playlist.clearPlaylist()}
      >
        <X class="h-4 w-4" />
      </button>
    </div>
  </div>
{/if}

// apps/web/src/components/collections/playlist-controller.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import {
  SkipForward,
  SkipBack,
  Shuffle,
  Repeat,
  X,
  ChevronUp,
  ChevronDown,
  Film,
  Images,
  Layers,
  Music,
} from "lucide-react";
import type { CollectionEntityType } from "@obscura/contracts";
import { usePlaylistContext } from "./playlist-context";
import { PlaylistQueueSheet } from "./playlist-queue-sheet";
import { getEntityHref } from "./collection-item-helpers";

const typeIcons: Record<CollectionEntityType, typeof Film> = {
  video: Film,
  gallery: Images,
  image: Layers,
  "audio-track": Music,
};

/**
 * Global floating playlist controller bar.
 * Renders at the bottom of the viewport when a playlist is active.
 * Shows current item, transport controls, and an expandable queue sheet.
 */
export function PlaylistController() {
  const playlist = usePlaylistContext();
  const [showQueue, setShowQueue] = useState(false);

  if (!playlist.isActive) return null;

  const currentTitle =
    (playlist.currentItem?.entity?.title as string) ?? "Untitled";
  const CurrentTypeIcon = playlist.currentItem
    ? typeIcons[playlist.currentItem.entityType]
    : Film;

  return (
    <>
      <PlaylistQueueSheet
        open={showQueue}
        onClose={() => setShowQueue(false)}
      />

      {/* Controller bar — sits above MobileNav on mobile */}
      <div className="fixed bottom-14 md:bottom-0 left-0 right-0 z-[55] bg-surface-1/95 backdrop-blur-xl border-t border-border-subtle h-14 flex items-center px-4 gap-3">
        {/* Current item info */}
        <div className="flex items-center gap-2 min-w-0 flex-1">
          <CurrentTypeIcon className="h-4 w-4 text-text-accent flex-shrink-0" />
          <div className="min-w-0">
            <Link
              href={playlist.currentItem ? getEntityHref(playlist.currentItem) : "#"}
              className="text-[0.78rem] text-text-primary truncate font-medium leading-tight block hover:text-text-accent transition-colors"
            >
              {currentTitle}
            </Link>
            <Link
              href={`/collections/${playlist.collectionId}`}
              className="text-[0.65rem] text-text-muted truncate leading-tight block hover:text-text-accent transition-colors"
            >
              {playlist.collectionName} —{" "}
              {playlist.currentPosition + 1}/{playlist.items.length}
            </Link>
          </div>
        </div>

        {/* Transport controls */}
        <div className="flex items-center gap-1">
          <button
            onClick={playlist.toggleShuffle}
            className={`p-1.5 transition-colors ${
              playlist.shuffle
                ? "text-text-accent"
                : "text-text-muted hover:text-text-secondary"
            }`}
            title="Shuffle"
          >
            <Shuffle className="h-3.5 w-3.5" />
          </button>

          <button
            onClick={playlist.previous}
            className="p-1.5 text-text-secondary hover:text-text-primary transition-colors"
            title="Previous"
          >
            <SkipBack className="h-4 w-4" />
          </button>

          <button
            onClick={playlist.next}
            className="p-1.5 text-text-secondary hover:text-text-primary transition-colors"
            title="Next"
          >
            <SkipForward className="h-4 w-4" />
          </button>

          <button
            onClick={playlist.toggleLoop}
            className={`p-1.5 transition-colors ${
              playlist.loop
                ? "text-text-accent"
                : "text-text-muted hover:text-text-secondary"
            }`}
            title="Loop"
          >
            <Repeat className="h-3.5 w-3.5" />
          </button>
        </div>

        {/* Queue toggle & dismiss */}
        <div className="flex items-center gap-1">
          <button
            onClick={() => setShowQueue((s) => !s)}
            className="p-1.5 text-text-muted hover:text-text-secondary transition-colors"
            title="Queue"
          >
            {showQueue ? (
              <ChevronDown className="h-4 w-4" />
            ) : (
              <ChevronUp className="h-4 w-4" />
            )}
          </button>
          <button
            onClick={playlist.clearPlaylist}
            className="p-1.5 text-text-muted hover:text-error-text transition-colors"
            title="End playlist"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>
    </>
  );
}
