// apps/web/src/components/collections/collection-card.tsx
"use client";

import Link from "next/link";
import {
  FolderOpen,
  Film,
  Images,
  Music,
  Layers,
  Zap,
  Hand,
  Shuffle,
} from "lucide-react";
import { cn } from "@obscura/ui/lib/utils";
import type { CollectionListItemDto, CollectionEntityType } from "@obscura/contracts";
import { toApiUrl } from "../../lib/api/core";

interface CollectionCardProps {
  collection: CollectionListItemDto;
  variant?: "grid" | "list";
}

const modeIcons = {
  manual: Hand,
  dynamic: Zap,
  hybrid: Shuffle,
} as const;

const modeLabels = {
  manual: "Manual",
  dynamic: "Dynamic",
  hybrid: "Hybrid",
} as const;

const typeIcons: Record<CollectionEntityType, typeof Film> = {
  video: Film,
  gallery: Images,
  image: Layers,
  "audio-track": Music,
};

export function CollectionCard({
  collection,
  variant = "grid",
}: CollectionCardProps) {
  if (variant === "list") {
    return <CollectionListCard collection={collection} />;
  }
  return <CollectionGridCard collection={collection} />;
}

function CollectionGridCard({
  collection,
}: {
  collection: CollectionListItemDto;
}) {
  const ModeIcon = modeIcons[collection.mode] ?? FolderOpen;
  const coverUrl = collection.coverImagePath
    ? toApiUrl(collection.coverImagePath)
    : null;

  const typeCounts = collection.typeCounts;
  const activeTypes = (
    Object.entries(typeCounts) as [CollectionEntityType, number][]
  ).filter(([, count]) => count > 0);

  return (
    <Link href={`/collections/${collection.id}`} className="block h-full">
      <div className="surface-card media-card-shell group relative h-full overflow-hidden">
        {/* Cover / Mosaic */}
        <div className="relative aspect-video overflow-hidden bg-surface-2">
          {coverUrl ? (
            <img
              src={coverUrl}
              alt={collection.name}
              className="h-full w-full object-cover"
            />
          ) : (
            <div className="flex h-full w-full items-center justify-center">
              <FolderOpen className="h-12 w-12 text-text-disabled" />
            </div>
          )}

          {/* Mode badge */}
          <div className="absolute top-2 right-2 flex items-center gap-1 px-1.5 py-0.5 text-[0.65rem] font-mono uppercase tracking-wider bg-surface-1/80 backdrop-blur-sm text-text-secondary">
            <ModeIcon className="h-3 w-3" />
            {modeLabels[collection.mode]}
          </div>

          {/* Item count */}
          <div className="absolute bottom-2 left-2 px-1.5 py-0.5 text-[0.65rem] font-mono bg-surface-1/80 backdrop-blur-sm text-text-secondary">
            {collection.itemCount} items
          </div>
        </div>

        {/* Info */}
        <div className="p-2.5 space-y-1.5">
          <h3 className="font-heading text-sm font-medium text-text-primary truncate leading-tight">
            {collection.name}
          </h3>

          {collection.description && (
            <p className="text-text-muted text-[0.7rem] line-clamp-2 leading-relaxed">
              {collection.description}
            </p>
          )}

          {/* Type breakdown chips */}
          {activeTypes.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {activeTypes.map(([type, count]) => {
                const Icon = typeIcons[type];
                return (
                  <span
                    key={type}
                    className="inline-flex items-center gap-0.5 px-1.5 py-0.5 text-[0.6rem] font-mono text-text-muted bg-surface-2"
                  >
                    <Icon className="h-2.5 w-2.5" />
                    {count}
                  </span>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </Link>
  );
}

function CollectionListCard({
  collection,
}: {
  collection: CollectionListItemDto;
}) {
  const ModeIcon = modeIcons[collection.mode] ?? FolderOpen;
  const coverUrl = collection.coverImagePath
    ? toApiUrl(collection.coverImagePath)
    : null;

  const typeCounts = collection.typeCounts;
  const activeTypes = (
    Object.entries(typeCounts) as [CollectionEntityType, number][]
  ).filter(([, count]) => count > 0);

  return (
    <Link
      href={`/collections/${collection.id}`}
      className="flex items-center gap-3 p-2 surface-card hover:bg-surface-2 transition-colors duration-fast"
    >
      {/* Thumbnail */}
      <div className="h-12 w-20 flex-shrink-0 overflow-hidden bg-surface-2">
        {coverUrl ? (
          <img
            src={coverUrl}
            alt={collection.name}
            className="h-full w-full object-cover"
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center">
            <FolderOpen className="h-5 w-5 text-text-disabled" />
          </div>
        )}
      </div>

      {/* Info */}
      <div className="flex-1 min-w-0">
        <h3 className="font-heading text-sm font-medium text-text-primary truncate">
          {collection.name}
        </h3>
        <div className="flex items-center gap-2 text-[0.7rem] text-text-muted">
          <span className="inline-flex items-center gap-0.5">
            <ModeIcon className="h-3 w-3" />
            {modeLabels[collection.mode]}
          </span>
          <span>{collection.itemCount} items</span>
          {activeTypes.map(([type, count]) => {
            const Icon = typeIcons[type];
            return (
              <span key={type} className="inline-flex items-center gap-0.5">
                <Icon className="h-2.5 w-2.5" />
                {count}
              </span>
            );
          })}
        </div>
      </div>
    </Link>
  );
}

// apps/web-svelte/src/lib/media-surface/configs/CollectionCard.svelte
<script lang="ts">
  import { Badge, Checkbox, cn } from "@obscura/ui-svelte";
  import type { CollectionListItemDto } from "@obscura/contracts";
  import type { CardProps } from "$lib/media-surface/config";
  import CollectionThumbnail from "$lib/components/thumbnails/CollectionThumbnail.svelte";

  let {
    item,
    index,
    selected = false,
    onToggleSelect,
    layout = "grid",
  }: CardProps<CollectionListItemDto> = $props();
</script>

{#if layout === "list"}
  <div class={cn(
    "flex items-center gap-3 px-3 py-2 surface-panel",
    selected && "bg-accent-950"
  )}>
    {#if onToggleSelect}
      <Checkbox checked={selected} onchange={() => onToggleSelect?.()} />
    {/if}
    <a href={`/collections/${item.id}`} class="w-16 shrink-0">
      <CollectionThumbnail collection={item} gradientIndex={index} size="list" />
    </a>
    <a
      href={`/collections/${item.id}`}
      class="min-w-0 flex-1 text-[0.82rem] font-medium text-text-primary hover:text-text-accent"
    >
      {item.name}
    </a>
    <span class="text-[0.68rem] text-text-muted">
      {item.itemCount} item{item.itemCount === 1 ? "" : "s"}
    </span>
    <Badge>{item.mode}</Badge>
  </div>
{:else}
  <a
    href={`/collections/${item.id}`}
    class="surface-card-sharp overflow-hidden hover:border-border-accent transition-colors duration-fast block"
  >
    <CollectionThumbnail collection={item} gradientIndex={index} />
    <div class="p-2.5 space-y-1">
      <h4 class="truncate text-body font-medium text-text-primary">{item.name}</h4>
      <div class="flex items-center gap-1.5 text-[0.65rem] text-text-muted">
        <span>{item.itemCount} item{item.itemCount === 1 ? "" : "s"}</span>
        <Badge>{item.mode}</Badge>
      </div>
    </div>
  </a>
{/if}
