// apps/web/src/components/gallery-card.tsx
"use client";

import { useRef, useState, useCallback } from "react";
import { Images, FolderOpen, Archive, Sparkles } from "lucide-react";
import { cn } from "@obscura/ui/lib/utils";
import { toApiUrl } from "../lib/api";
import type { GalleryListItemDto } from "@obscura/contracts";

const typeIcons = {
  folder: FolderOpen,
  zip: Archive,
  virtual: Sparkles,
} as const;

interface GalleryCardProps {
  gallery: GalleryListItemDto;
}

export function GalleryCard({ gallery }: GalleryCardProps) {
  const [currentPreviewIndex, setCurrentPreviewIndex] = useState(-1);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const coverUrl = toApiUrl(gallery.coverImagePath);
  const previews = gallery.previewImagePaths?.map(toApiUrl).filter(Boolean) ?? [];

  const startScrub = useCallback(() => {
    if (previews.length <= 1) return;
    let idx = 0;
    setCurrentPreviewIndex(0);
    intervalRef.current = setInterval(() => {
      idx = (idx + 1) % previews.length;
      setCurrentPreviewIndex(idx);
    }, 800);
  }, [previews.length]);

  const stopScrub = useCallback(() => {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
    setCurrentPreviewIndex(-1);
  }, []);

  const displayUrl = currentPreviewIndex >= 0 ? previews[currentPreviewIndex] : coverUrl;
  const TypeIcon = typeIcons[gallery.galleryType] ?? FolderOpen;

  return (
    <div
      className="surface-card-sharp media-card-shell group relative overflow-hidden"
      onPointerEnter={startScrub}
      onPointerLeave={stopScrub}
    >
      {/* Cover image */}
      <div className="relative aspect-[4/3] bg-surface-2 overflow-hidden">
        {displayUrl ? (
          <img
            src={displayUrl}
            alt={gallery.title}
            className="h-full w-full object-cover transition-opacity duration-fast"
            loading="lazy"
            decoding="async"
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center">
            <Images className="h-10 w-10 text-text-disabled" />
          </div>
        )}

        {/* Image count badge */}
        <div className="absolute bottom-1.5 left-1.5 flex items-center gap-1 rounded-sm bg-black/70 px-1.5 py-0.5 text-[0.65rem] text-white/90 backdrop-blur-sm">
          <Images className="h-3 w-3" />
          {gallery.imageCount}
        </div>

        {/* Type badge */}
        <div className="absolute top-1.5 right-1.5 rounded-sm bg-black/60 p-1 backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-opacity duration-fast">
          <TypeIcon className="h-3 w-3 text-white/80" />
        </div>

        {/* Scrub progress bar */}
        {currentPreviewIndex >= 0 && previews.length > 1 && (
          <div className="absolute bottom-0 left-0 right-0 flex gap-0.5 px-1 pb-0.5">
            {previews.map((_, i) => (
              <div
                key={i}
                className={cn(
                  "h-0.5 flex-1 rounded-full transition-colors duration-fast",
                  i === currentPreviewIndex ? "bg-accent-500" : "bg-white/30"
                )}
              />
            ))}
          </div>
        )}
      </div>

      {/* Card body */}
      <div className="px-2.5 py-2">
        <h3 className="text-[0.78rem] font-medium text-text-primary truncate">
          {gallery.title}
        </h3>
        <div className="flex items-center gap-2 mt-0.5">
          {gallery.date && (
            <span className="text-[0.65rem] text-text-muted">{gallery.date}</span>
          )}
          {gallery.rating != null && (
            <span className="text-[0.65rem] text-accent-500">{"★".repeat(Math.round(gallery.rating / 20))}</span>
          )}
        </div>
        {gallery.tags.length > 0 && (
          <div className="flex flex-wrap gap-1 mt-1.5">
            {gallery.tags.slice(0, 3).map((tag) => (
              <span key={tag.id} className="tag-chip tag-chip-default text-[0.55rem]">
                {tag.name}
              </span>
            ))}
            {gallery.tags.length > 3 && (
              <span className="text-[0.55rem] text-text-disabled">+{gallery.tags.length - 3}</span>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// apps/web-svelte/src/lib/media-surface/configs/GalleryCard.svelte
<script lang="ts">
  import { Badge, Checkbox } from "@obscura/ui-svelte";
  import { Images, Layers } from "@lucide/svelte";
  import type { GalleryListItemDto } from "@obscura/contracts";
  import type { CardProps } from "$lib/media-surface/config";
  import EntityThumbnail from "$lib/v1/components/thumbnails/EntityThumbnailV1.svelte";
  import { VIDEO_CARD_GRADIENTS } from "$lib/dashboard-utils";

  let {
    item,
    index,
    selected = false,
    onToggleSelect,
    layout = "grid",
  }: CardProps<GalleryListItemDto> = $props();

  const gradient = $derived(VIDEO_CARD_GRADIENTS[index % VIDEO_CARD_GRADIENTS.length]);
  const previewBackedSeries = $derived(item.imageCount === 0 && item.previewImagePaths.length > 0);
  const coverAspectRatio = $derived(
    previewBackedSeries && !item.isComic ? item.coverAspectRatio : null,
  );
</script>

{#if layout === "list"}
  <div class="relative">
    {#if onToggleSelect}
      <button
        type="button"
        class="absolute left-1.5 top-1/2 z-10 flex h-7 w-7 -translate-y-1/2 items-center justify-center glass-2 border border-border-subtle"
        onclick={() => onToggleSelect?.()}
        aria-label={`Select ${item.title}`}
      >
        <Checkbox checked={selected} />
      </button>
    {/if}
    <a
      href={`/galleries/${item.id}`}
      class="flex items-center gap-3 py-2 pl-11 pr-3 text-body-sm hover:bg-surface-2 transition-colors duration-fast"
    >
      <div class="w-20 shrink-0">
        <EntityThumbnail
          kind="gallery"
          title={item.title}
          coverImagePath={item.coverImagePath}
          previewImagePaths={item.previewImagePaths}
          imageCount={item.imageCount}
          isNsfw={item.isNsfw}
          isComic={item.isComic}
          rating={item.rating}
          size="list"
          aspectRatio={coverAspectRatio}
          fit={item.isComic || previewBackedSeries ? "contain" : "cover"}
          gradientFallback={gradient}
          showCount={false}
        />
      </div>
      <div class="flex-1 min-w-0">
        <div class="truncate text-text-primary">{item.title}</div>
        <div class="flex flex-wrap items-center gap-x-2 gap-y-1 text-[0.7rem] text-text-muted mt-0.5">
          {#if item.imageCount > 0}
            <span class="inline-flex items-center gap-1">
              <Images class="h-3 w-3" />
              {item.imageCount} image{item.imageCount === 1 ? "" : "s"}
            </span>
          {/if}
          {#if item.childCount > 0}
            <span class="inline-flex items-center gap-1">
              <Layers class="h-3 w-3" />
              {item.childCount} {item.childCount === 1 ? "sub-gallery" : "sub-galleries"}
            </span>
          {/if}
          {#if item.studioName}<span class="text-text-accent truncate">· {item.studioName}</span>{/if}
          {#if item.date}<span>· {item.date}</span>{/if}
        </div>
      </div>
      {#if item.isNsfw}<Badge variant="warning">NSFW</Badge>{/if}
    </a>
  </div>
{:else}
  <div class="relative">
    {#if onToggleSelect}
      <button
        type="button"
        class="absolute left-1.5 top-1.5 z-20 flex h-7 w-7 items-center justify-center glass-2 border border-border-subtle shadow-[var(--shadow-soft)]"
        onclick={() => onToggleSelect?.()}
        aria-label={`Select ${item.title}`}
      >
        <Checkbox checked={selected} />
      </button>
    {/if}
    <a
      href={`/galleries/${item.id}`}
      class="surface-card-sharp overflow-hidden hover:border-border-accent transition-colors duration-fast block"
    >
      <div class={onToggleSelect ? "p-1" : ""}>
        <EntityThumbnail
          kind="gallery"
          title={item.title}
          coverImagePath={item.coverImagePath}
          previewImagePaths={item.previewImagePaths}
          imageCount={item.imageCount}
          isNsfw={item.isNsfw}
          isComic={item.isComic}
          rating={item.rating}
          size="grid"
          aspectRatio={coverAspectRatio}
          aspectClass={previewBackedSeries && !item.isComic ? "aspect-[4/3]" : undefined}
          fit={item.isComic || previewBackedSeries ? "contain" : "cover"}
          gradientFallback={gradient}
          showCount={false}
        />
      </div>
      <div class="p-2.5 space-y-1">
        <h4 class="truncate text-body font-medium text-text-primary">{item.title}</h4>
        <div class="flex flex-wrap items-center gap-x-2 gap-y-1 text-[0.65rem] text-text-muted">
          {#if item.imageCount > 0}
            <span class="inline-flex items-center gap-1">
              <Images class="h-3 w-3" />
              {item.imageCount} image{item.imageCount === 1 ? "" : "s"}
            </span>
          {/if}
          {#if item.childCount > 0}
            <span class="inline-flex items-center gap-1">
              <Layers class="h-3 w-3" />
              {item.childCount} {item.childCount === 1 ? "sub-gallery" : "sub-galleries"}
            </span>
          {/if}
          {#if item.studioName}<span class="text-text-accent truncate">· {item.studioName}</span>{/if}
        </div>
      </div>
    </a>
  </div>
{/if}
